# Google Drive

In [1]:
# # G D R I V E
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

# Installations

In [2]:
# BioPython (Data Gathering)
!pip install biopython
!pip install --upgrade biopython

Collecting biopython
  Downloading https://files.pythonhosted.org/packages/3a/cd/0098eaff841850c01da928c7f509b72fd3e1f51d77b772e24de9e2312471/biopython-1.78-cp37-cp37m-manylinux1_x86_64.whl (2.3MB)
     |████████████████████████████████| 2.3MB 11.8MB/s
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from biopython) (1.19.5)
Installing collected packages: biopython
Successfully installed biopython-1.78
Requirement already up-to-date: biopython in /usr/local/lib/python3.7/dist-packages (1.78)
Requirement already satisfied, skipping upgrade: numpy in /usr/local/lib/python3.7/dist-packages (from biopython) (1.19.5)

In [3]:
# Libraries
from Bio import SeqIO
import numpy as np
import pandas as pd
import os, glob
import seaborn as sns
import matplotlib.pyplot as plt
from multiprocessing import Pool
from tqdm import tqdm
from itertools import groupby
from sklearn.decomposition import LatentDirichletAllocation as LDA
from sklearn.feature_extraction.text import CountVectorizer
import math
import json
from functools import partial
from collections import defaultdict

In [4]:
tqdm = partial(tqdm, position=0, leave=True)

# Data Gathering

In [6]:
# Directories
folder_path = "/content/drive/MyDrive/semantic_browser/COVID/Metadata_07-03-2021/"
clades_folders = os.listdir(folder_path)
clades_folders = [x for x in clades_folders if ".gdoc" not in x]
clades_folders = [x for x in clades_folders if ".ipynb_checkpoints" not in x]
clades_folders

['G', 'GR', 'GH', 'GV', 'L', 'S', 'O', 'V', 'GRY']

In [7]:
clade = []
seq = []
id = []
size = []
location = []

for x in clades_folders:
  archive_list = os.listdir(folder_path + x)
  #print(archive_list)# total files/clade folder
  for k in archive_list:
    filename = folder_path + x + "/" + k
    #print(filename) # all file pathways
    #print(k) # all filenames
    for seq_record in SeqIO.parse(filename, "fasta"):
      clade.append(x)
      seq.append(str(seq_record.seq)) 
      id.append(seq_record.id)
      size.append(len(seq_record))
      location.append(k)

In [8]:
# Generate Pandas DataFrame from list of dictionaries
dictionary = {'id': id, 'seq': seq, 'clade': clade, \
              'location': location, 'size': size}
Data_Frame = pd.DataFrame.from_dict(dictionary)

In [9]:
Data_Frame

                                                     id  ...   size
0     hCoV-19/Aruba/AW-RIVM-11761/2021|EPI_ISL_10138...  ...  29782
1     hCoV-19/Aruba/AW-RIVM-11767/2021|EPI_ISL_10138...  ...  29782
2     hCoV-19/Aruba/AW-RIVM-11740/2021|EPI_ISL_10146...  ...  29782
3     hCoV-19/Aruba/AW-RIVM-11736/2021|EPI_ISL_10146...  ...  29782
4     hCoV-19/Aruba/AW-RIVM-11610/2021|EPI_ISL_10146...  ...  29782
...                                                 ...  ...    ...
9466                                       hCoV-19/Sint  ...  29763
9467                                       hCoV-19/Sint  ...  29763
9468                                       hCoV-19/Sint  ...  29763
9469                                       hCoV-19/Sint  ...  29763
9470                                       hCoV-19/Sint  ...  29763

[9471 rows x 5 columns]

In [10]:
Data_Frame.to_csv('COVID_LATAM_complete.csv')

# Data Import

In [11]:
Data_Frame = pd.read_csv("/content/drive/MyDrive/semantic_browser/COVID/"\
                         "Metadata_07-03-2021/COVID_LATAM_complete.csv", index_col=0)
Data_Frame

                                                     id  ...   size
0     hCoV-19/Aruba/AW-RIVM-11761/2021|EPI_ISL_10138...  ...  29782
1     hCoV-19/Aruba/AW-RIVM-11767/2021|EPI_ISL_10138...  ...  29782
2     hCoV-19/Aruba/AW-RIVM-11740/2021|EPI_ISL_10146...  ...  29782
3     hCoV-19/Aruba/AW-RIVM-11736/2021|EPI_ISL_10146...  ...  29782
4     hCoV-19/Aruba/AW-RIVM-11610/2021|EPI_ISL_10146...  ...  29782
...                                                 ...  ...    ...
9466                                       hCoV-19/Sint  ...  29763
9467                                       hCoV-19/Sint  ...  29763
9468                                       hCoV-19/Sint  ...  29763
9469                                       hCoV-19/Sint  ...  29763
9470                                       hCoV-19/Sint  ...  29763

[9471 rows x 5 columns]

In [25]:
# Filter by location
Data_Frame['mask'] = Data_Frame['location'].str.contains('V_') 
len(Data_Frame.loc[(Data_Frame['mask'] == True)])
#Data_Frame.drop(['mask'], axis=1)
#print(Data_Frame.iloc[0])

69

# K-mer Decomposition

In [27]:
def k_mer_decomposition(Nucleotide_Sequence, k): # Function to decomposition into k-mers
    Pre_Vocabulary = list(Nucleotide_Sequence[0+i:k+i] for i in range(0, len(Nucleotide_Sequence)- k + 1))
    Extended_Nomenclature_Nucleotides = ['U', 'W', 'S', 'M', 'K', 'R', 'Y', 'B', 'D', 'H', 'V', 'N']
    # To remove the nucleotide extended nomenclature 
    Vocabulary = [words for words in Pre_Vocabulary if all(Nucleotide not in words for Nucleotide in Extended_Nomenclature_Nucleotides)] 
    return Vocabulary

In [28]:
# k-mers path
PATH_files = "/content/drive/MyDrive/semantic_browser/COVID/Metadata_07-03-2021/k-mers/"

In [29]:
k_mer_size = 9
#k_mers = []

batch = 1000
int_value = math.floor(len(Data_Frame)/batch)
for k in tqdm(range(int_value)):
  k_mers = []
  start = k*batch
  end = k*batch+batch
  for x in tqdm(range(start,end)):
    k_mers_list = k_mer_decomposition(Data_Frame['seq'].iloc[x], k_mer_size) # Decompose the genome into overlapped k-mers
    k_mers_string = ' '.join(k_mers_list)
    k_mers.append(k_mers_string)
  with open(PATH_files + str(x) + "_kmer.txt", "w") as fp:   #Serialize
    json.dump(k_mers, fp)

k_mers = []
for a in tqdm(range(end,end+len(Data_Frame)-x)):
  k_mers_list = k_mer_decomposition(Data_Frame['seq'].iloc[x], k_mer_size) # Decompose the genome into overlapped k-mers
  k_mers_string = ' '.join(k_mers_list)
  k_mers.append(k_mers_string)
with open(PATH_files + str(a) + "_kmer.txt", "w") as fp:   #Serialize
  json.dump(k_mers, fp)

100%|██████████| 1000/1000 [00:43<00:00, 22.83it/s]
100%|██████████| 1000/1000 [00:45<00:00, 22.16it/s]
100%|██████████| 1000/1000 [00:45<00:00, 21.79it/s]
100%|██████████| 1000/1000 [00:47<00:00, 20.99it/s]
100%|██████████| 1000/1000 [00:45<00:00, 22.01it/s]
100%|██████████| 1000/1000 [00:45<00:00, 21.89it/s]
100%|██████████| 1000/1000 [00:44<00:00, 22.28it/s]
100%|██████████| 1000/1000 [00:45<00:00, 22.15it/s]
100%|██████████| 1000/1000 [00:45<00:00, 22.15it/s]
100%|██████████| 9/9 [07:17<00:00, 48.60s/it]
100%|██████████| 472/472 [00:21<00:00, 21.58it/s]

# K-mer files into DataFrame

In [ ]:
# Directories
folder_path = "/content/drive/MyDrive/semantic_browser/COVID/k_mers"
file_list = os.listdir(folder_path)
file_list = [x for x in file_list if ".ipynb_checkpoints" not in x]
file_list

['999_kmer.txt',
 '1999_kmer.txt',
 '2999_kmer.txt',
 '3999_kmer.txt',
 '4999_kmer.txt',
 '5999_kmer.txt',
 '6999_kmer.txt',
 '7999_kmer.txt',
 '8999_kmer.txt',
 '9999_kmer.txt',
 '10999_kmer.txt',
 '11999_kmer.txt',
 '12999_kmer.txt',
 '13999_kmer.txt',
 '14999_kmer.txt',
 '15999_kmer.txt',
 '16999_kmer.txt',
 '17999_kmer.txt',
 '18999_kmer.txt',
 '19999_kmer.txt',
 '20999_kmer.txt',
 '21999_kmer.txt',
 '22999_kmer.txt',
 '23999_kmer.txt',
 '24999_kmer.txt',
 '25999_kmer.txt',
 '26999_kmer.txt',
 '27999_kmer.txt',
 '28999_kmer.txt',
 '29999_kmer.txt',
 '30999_kmer.txt',
 '31999_kmer.txt',
 '32999_kmer.txt',
 '33999_kmer.txt',
 '34999_kmer.txt',
 '35999_kmer.txt',
 '36999_kmer.txt',
 '37999_kmer.txt',
 '38999_kmer.txt',
 '39999_kmer.txt',
 '40999_kmer.txt',
 '41999_kmer.txt',
 '42999_kmer.txt',
 '43999_kmer.txt',
 '44999_kmer.txt',
 '45999_kmer.txt',
 '46999_kmer.txt',
 '47999_kmer.txt',
 '48999_kmer.txt',
 '49999_kmer.txt',
 '50999_kmer.txt',
 '51999_kmer.txt',
 '52999_kmer.txt',
 '53999_kmer.txt',
 '54999_kmer.txt',
 '55999_kmer.txt',
 '56999_kmer.txt',
 '57999_kmer.txt',
 '58999_kmer.txt',
 '59999_kmer.txt',
 '60999_kmer.txt',
 '61999_kmer.txt',
 '62999_kmer.txt',
 '63999_kmer.txt',
 '64999_kmer.txt',
 '65999_kmer.txt',
 '66999_kmer.txt',
 '67999_kmer.txt',
 '68999_kmer.txt',
 '69999_kmer.txt',
 '70999_kmer.txt',
 '71999_kmer.txt',
 '72999_kmer.txt',
 '73999_kmer.txt',
 '74999_kmer.txt',
 '75999_kmer.txt',
 '76999_kmer.txt',
 '77999_kmer.txt',
 '78999_kmer.txt',
 '79999_kmer.txt',
 '80999_kmer.txt',
 '81999_kmer.txt',
 '82999_kmer.txt',
 '83999_kmer.txt',
 '84999_kmer.txt',
 '85999_kmer.txt',
 '86999_kmer.txt',
 '87999_kmer.txt',
 '88999_kmer.txt',
 '89383_kmer.txt']

In [ ]:
# Get all filenames
PATH_files = "/content/drive/MyDrive/semantic_browser/COVID/"
filenames = []
for x in tqdm(file_list[0:3]):
  filenames.append(folder_path + "/" + x)

# Create iterable object (generator)
def read_using_generator(filenames):
  read_file = []
  for i in tqdm(filenames):
    with open(i, "r") as fp:   # Unpickling
      read_file_aux = json.load(fp)
    read_file += read_file_aux
  yield (read_file)

read_files = read_using_generator(filenames)

k_mer_list = []
for kmer_file in tqdm(read_files):
  k_mer_list += kmer_file

100%|██████████| 3/3 [00:00<00:00, 1059.97it/s]
100%|██████████| 3/3 [00:08<00:00,  2.82s/it]
1it [00:08,  8.47s/it]

In [ ]:
print(k_mer_list[0])

ATTAAAGGT TTAAAGGTT TAAAGGTTT AAAGGTTTA AAGGTTTAT AGGTTTATA GGTTTATAC GTTTATACC TTTATACCT TTATACCTT TATACCTTC ATACCTTCC TACCTTCCC ACCTTCCCA CCTTCCCAG CTTCCCAGG TTCCCAGGT TCCCAGGTA CCCAGGTAA CCAGGTAAC CAGGTAACA AGGTAACAA GGTAACAAA GTAACAAAC TAACAAACC AACAAACCA ACAAACCAA CAAACCAAC AAACCAACC AACCAACCA ACCAACCAA CCAACCAAC CAACCAACT AACCAACTT ACCAACTTT CCAACTTTC CAACTTTCG AACTTTCGA ACTTTCGAT CTTTCGATC TTTCGATCT TTCGATCTC TCGATCTCT CGATCTCTT GATCTCTTG ATCTCTTGT TCTCTTGTA CTCTTGTAG TCTTGTAGA CTTGTAGAT TTGTAGATC TGTAGATCT GTAGATCTG TAGATCTGT AGATCTGTT GATCTGTTC ATCTGTTCT TCTGTTCTC CTGTTCTCT TGTTCTCTA GTTCTCTAA TTCTCTAAA TCTCTAAAC CTCTAAACG TCTAAACGA CTAAACGAA TAAACGAAC AAACGAACT AACGAACTT ACGAACTTT CGAACTTTA GAACTTTAA AACTTTAAA ACTTTAAAA CTTTAAAAT TTTAAAATC TTAAAATCT TAAAATCTG AAAATCTGT AAATCTGTG AATCTGTGT ATCTGTGTG TCTGTGTGG CTGTGTGGC TGTGTGGCT GTGTGGCTG TGTGGCTGT GTGGCTGTC TGGCTGTCA GGCTGTCAC GCTGTCACT CTGTCACTC TGTCACTCG GTCACTCGG TCACTCGGC CACTCGGCT ACTCGGCTG CTCGGCTGC TCGGCTGCA CGGCTGCAT GGCTGCATG GCTGCATGC CTGCATGCT TGCATGCTT GCATGCTTA CATGCTTAG ATGCTTAGT TGCTTAGTG GCTTAGTGC CTTAGTGCA TTAGTGCAC TAGTGCACT AGTGCACTC GTGCACTCA TGCACTCAC GCACTCACG CACTCACGC ACTCACGCA CTCACGCAG TCACGCAGT CACGCAGTA ACGCAGTAT CGCAGTATA GCAGTATAA CAGTATAAT AGTATAATT GTATAATTA TATAATTAA ATAATTAAT TAATTAATA AATTAATAA ATTAATAAC TTAATAACT TAATAACTA AATAACTAA ATAACTAAT TAACTAATT AACTAATTA ACTAATTAC CTAATTACT TAATTACTG AATTACTGT ATTACTGTC TTACTGTCG TACTGTCGT ACTGTCGTT CTGTCGTTG TGTCGTTGA GTCGTTGAC TCGTTGACA CGTTGACAG GTTGACAGG TTGACAGGA TGACAGGAC GACAGGACA ACAGGACAC CAGGACACG AGGACACGA GGACACGAG GACACGAGT ACACGAGTA CACGAGTAA ACGAGTAAC CGAGTAACT GAGTAACTC AGTAACTCG GTAACTCGT TAACTCGTC AACTCGTCT ACTCGTCTA CTCGTCTAT TCGTCTATC CGTCTATCT GTCTATCTT TCTATCTTC CTATCTTCT TATCTTCTG ATCTTCTGC TCTTCTGCA CTTCTGCAG TTCTGCAGG TCTGCAGGC CTGCAGGCT TGCAGGCTG GCAGGCTGC CAGGCTGCT AGGCTGCTT GGCTGCTTA GCTGCTTAC CTGCTTACG TGCTTACGG GCTTACGGT CTTACGGTT TTACGGTTT TACGGTTTC ACGGTTTCG CGGTTTCGT GGTTTCGTC GTTTCGTCC TTTCGTCCG TTCGTCCGT TCGTCCGTG CGTCCGTGT GTCCGTGTT TCCGTGTTG CCGTGTTGC CGTGTTGCA GTGTTGCAG TGTTGCAGC GTTGCAGCC TTGCAGCCG TGCAGCCGA GCAGCCGAT CAGCCGATC AGCCGATCA GCCGATCAT CCGATCATC CGATCATCA GATCATCAG ATCATCAGC TCATCAGCA CATCAGCAC ATCAGCACA TCAGCACAT CAGCACATC AGCACATCT GCACATCTA CACATCTAG ACATCTAGG CATCTAGGT ATCTAGGTT TCTAGGTTT CTAGGTTTT TAGGTTTTG AGGTTTTGT GGTTTTGTC GTTTTGTCC TTTTGTCCG TTTGTCCGG TTGTCCGGG TGTCCGGGT GTCCGGGTG TCCGGGTGT CCGGGTGTG CGGGTGTGA GGGTGTGAC GGTGTGACC GTGTGACCG TGTGACCGA GTGACCGAA TGACCGAAA GACCGAAAG ACCGAAAGG CCGAAAGGT CGAAAGGTA GAAAGGTAA AAAGGTAAG AAGGTAAGA AGGTAAGAT GGTAAGATG GTAAGATGG TAAGATGGA AAGATGGAG AGATGGAGA GATGGAGAG ATGGAGAGC TGGAGAGCC GGAGAGCCT GAGAGCCTT AGAGCCTTG GAGCCTTGT AGCCTTGTC GCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTG TGTCCCTGG GTCCCTGGT TCCCTGGTT CCCTGGTTT CCTGGTTTC CTGGTTTCA TGGTTTCAA GGTTTCAAC GTTTCAACG TTTCAACGA TTCAACGAG TCAACGAGA CAACGAGAA AACGAGAAA ACGAGAAAA CGAGAAAAC GAGAAAACA AGAAAACAC GAAAACACA AAAACACAC AAACACACG AACACACGT ACACACGTC CACACGTCC ACACGTCCA CACGTCCAA ACGTCCAAC CGTCCAACT GTCCAACTC TCCAACTCA CCAACTCAG CAACTCAGT AACTCAGTT ACTCAGTTT CTCAGTTTG TCAGTTTGC CAGTTTGCC AGTTTGCCT GTTTGCCTG TTTGCCTGT TTGCCTGTT TGCCTGTTT GCCTGTTTT CCTGTTTTA CTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGG TTTACAGGT TTACAGGTT TACAGGTTC ACAGGTTCG CAGGTTCGC AGGTTCGCG GGTTCGCGA GTTCGCGAC TTCGCGACG TCGCGACGT CGCGACGTG GCGACGTGC CGACGTGCT GACGTGCTC ACGTGCTCG CGTGCTCGT GTGCTCGTA TGCTCGTAC GCTCGTACG CTCGTACGT TCGTACGTG CGTACGTGG GTACGTGGC TACGTGGCT ACGTGGCTT CGTGGCTTT GTGGCTTTG TGGCTTTGG GGCTTTGGA GCTTTGGAG CTTTGGAGA TTTGGAGAC TTGGAGACT TGGAGACTC GGAGACTCC GAGACTCCG AGACTCCGT GACTCCGTG ACTCCGTGG CTCCGTGGA TCCGTGGAG CCGTGGAGG CGTGGAGGA GTGGAGGAG TGGAGGAGG GGAGGAGGT GAGGAGGTC AGGAGGTCT GGAGGTCTT GAGGTCTTA AGGTCTTAT GGTCTTATC GTCTTATCA TCTTATCAG CTTATCAGA TTATCAGAG TATCAGAGG ATCAGAGGC TCAGAGGCA CAGAGGCAC AGAGGCACG GAGGCACGT AGGCACGTC GGCACGTCA GCACGTCAA CACGTCAAC ACGTCAACA CGTCAACAT GTCAACATC TCAACATCT CAACATCTT AACATCTTA ACATCTTAA CATCTTAAA ATCTTAAAG TCTTAAAGA CTTAAAGAT TTAAAGATG TAAAGATGG AAAGATGGC AAGATGGCA AGATGGCAC GATGGCACT ATGGCACTT TGGCACTTG GGCACTTGT GCACTTGTG CACTTGTGG ACTTGTGGC CTTGTGGCT TTGTGGCTT TGTGGCTTA GTGGCTTAG TGGCTTAGT GGCTTAGTA GCTTAGTAG CTTAGTAGA TTAGTAGAA TAGTAGAAG AGTAGAAGT GTAGAAGTT TAGAAGTTG AGAAGTTGA GAAGTTGAA AAGTTGAAA AGTTGAAAA GTTGAAAAA TTGAAAAAG TGAAAAAGG GAAAAAGGC AAAAAGGCG AAAAGGCGT AAAGGCGTT AAGGCGTTT AGGCGTTTT GGCGTTTTG GCGTTTTGC CGTTTTGCC GTTTTGCCT TTTTGCCTC TTTGCCTCA TTGCCTCAA TGCCTCAAC GCCTCAACT CCTCAACTT CTCAACTTG TCAACTTGA CAACTTGAA AACTTGAAC ACTTGAACA CTTGAACAG TTGAACAGC TGAACAGCC GAACAGCCC AACAGCCCT ACAGCCCTA CAGCCCTAT AGCCCTATG GCCCTATGT CCCTATGTG CCTATGTGT CTATGTGTT TATGTGTTC ATGTGTTCA TGTGTTCAT GTGTTCATC TGTTCATCA GTTCATCAA TTCATCAAA TCATCAAAC CATCAAACG ATCAAACGT TCAAACGTT CAAACGTTC AAACGTTCG AACGTTCGG ACGTTCGGA CGTTCGGAT GTTCGGATG TTCGGATGC TCGGATGCT CGGATGCTC GGATGCTCG GATGCTCGA ATGCTCGAA TGCTCGAAC GCTCGAACT CTCGAACTG TCGAACTGC CGAACTGCA GAACTGCAC AACTGCACC ACTGCACCT CTGCACCTC TGCACCTCA GCACCTCAT CACCTCATG ACCTCATGG CCTCATGGT CTCATGGTC TCATGGTCA CATGGTCAT ATGGTCATG TGGTCATGT GGTCATGTT GTCATGTTA TCATGTTAT CATGTTATG ATGTTATGG TGTTATGGT GTTATGGTT TTATGGTTG TATGGTTGA ATGGTTGAG TGGTTGAGC GGTTGAGCT GTTGAGCTG TTGAGCTGG TGAGCTGGT GAGCTGGTA AGCTGGTAG GCTGGTAGC CTGGTAGCA TGGTAGCAG GGTAGCAGA GTAGCAGAA TAGCAGAAC AGCAGAACT GCAGAACTC CAGAACTCG AGAACTCGA GAACTCGAA AACTCGAAG ACTCGAAGG CTCGAAGGC TCGAAGGCA CGAAGGCAT GAAGGCATT AAGGCATTC AGGCATTCA GGCATTCAG GCATTCAGT CATTCAGTA ATTCAGTAC TTCAGTACG TCAGTACGG CAGTACGGT AGTACGGTC GTACGGTCG TACGGTCGT ACGGTCGTA CGGTCGTAG GGTCGTAGT GTCGTAGTG TCGTAGTGG CGTAGTGGT GTAGTGGTG TAGTGGTGA AGTGGTGAG GTGGTGAGA TGGTGAGAC GGTGAGACA GTGAGACAC TGAGACACT GAGACACTT AGACACTTG GACACTTGG ACACTTGGT CACTTGGTG ACTTGGTGT CTTGGTGTC TTGGTGTCC TGGTGTCCT GGTGTCCTT GTGTCCTTG TGTCCTTGT GTCCTTGTC TCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTC TGTCCCTCA GTCCCTCAT TCCCTCATG CCCTCATGT CCTCATGTG CTCATGTGG TCATGTGGG CATGTGGGC ATGTGGGCG TGTGGGCGA GTGGGCGAA TGGGCGAAA GGGCGAAAT GGCGAAATA GCGAAATAC CGAAATACC GAAATACCA AAATACCAG AATACCAGT ATACCAGTG TACCAGTGG ACCAGTGGC CCAGTGGCT CAGTGGCTT AGTGGCTTA GTGGCTTAC TGGCTTACC GGCTTACCG GCTTACCGC CTTACCGCA TTACCGCAA TACCGCAAG ACCGCAAGG CCGCAAGGT CGCAAGGTT GCAAGGTTC CAAGGTTCT AAGGTTCTT AGGTTCTTC GGTTCTTCT GTTCTTCTT TTCTTCTTC TCTTCTTCG CTTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGA TCGTAAGAA CGTAAGAAC GTAAGAACG TAAGAACGG AAGAACGGT AGAACGGTA GAACGGTAA AACGGTAAT ACGGTAATA CGGTAATAA GGTAATAAA GTAATAAAG TAATAAAGG AATAAAGGA ATAAAGGAG TAAAGGAGC AAAGGAGCT AAGGAGCTG AGGAGCTGG GGAGCTGGT GAGCTGGTG AGCTGGTGG GCTGGTGGC CTGGTGGCC TGGTGGCCA GGTGGCCAT GTGGCCATA TGGCCATAG GGCCATAGT GCCATAGTT CCATAGTTA CATAGTTAC ATAGTTACG TAGTTACGG AGTTACGGC GTTACGGCG TTACGGCGC TACGGCGCC ACGGCGCCG CGGCGCCGA GGCGCCGAT GCGCCGATC CGCCGATCT GCCGATCTA CCGATCTAA CGATCTAAA GATCTAAAG ATCTAAAGT TCTAAAGTC CTAAAGTCA TAAAGTCAT AAAGTCATT AAGTCATTT AGTCATTTG GTCATTTGA TCATTTGAC CATTTGACT ATTTGACTT TTTGACTTA TTGACTTAG TGACTTAGG GACTTAGGC ACTTAGGCG CTTAGGCGA TTAGGCGAC TAGGCGACG AGGCGACGA GGCGACGAG GCGACGAGC CGACGAGCT GACGAGCTT ACGAGCTTG CGAGCTTGG GAGCTTGGC AGCTTGGCA GCTTGGCAC CTTGGCACT TTGGCACTG TGGCACTGA GGCACTGAT GCACTGATC CACTGATCC ACTGATCCT CTGATCCTT TGATCCTTA GATCCTTAT ATCCTTATG TCCTTATGA CCTTATGAA CTTATGAAG TTATGAAGA TATGAAGAT ATGAAGATT TGAAGATTT GAAGATTTT AAGATTTTC AGATTTTCA GATTTTCAA ATTTTCAAG TTTTCAAGA TTTCAAGAA TTCAAGAAA TCAAGAAAA CAAGAAAAC AAGAAAACT AGAAAACTG GAAAACTGG AAAACTGGA AAACTGGAA AACTGGAAC ACTGGAACA CTGGAACAC TGGAACACT GGAACACTA GAACACTAA AACACTAAA ACACTAAAC CACTAAACA ACTAAACAT CTAAACATA TAAACATAG AAACATAGC AACATAGCA ACATAGCAG CATAGCAGT ATAGCAGTG TAGCAGTGG AGCAGTGGT GCAGTGGTG CAGTGGTGT AGTGGTGTT GTGGTGTTA TGGTGTTAC GGTGTTACC GTGTTACCC TGTTACCCG GTTACCCGT TTACCCGTG TACCCGTGA ACCCGTGAA CCCGTGAAC CCGTGAACT CGTGAACTC GTGAACTCA TGAACTCAT GAACTCATG AACTCATGC ACTCATGCG CTCATGCGT TCATGCGTG CATGCGTGA ATGCGTGAG TGCGTGAGC GCGTGAGCT CGTGAGCTT GTGAGCTTA TGAGCTTAA GAGCTTAAC AGCTTAACG GCTTAACGG CTTAACGGA TTAACGGAG TAACGGAGG AACGGAGGG ACGGAGGGG CGGAGGGGC GGAGGGGCA GAGGGGCAT AGGGGCATA GGGGCATAC GGGCATACA GGCATACAC GCATACACT CATACACTC ATACACTCG TACACTCGC ACACTCGCT CACTCGCTA ACTCGCTAT CTCGCTATG TCGCTATGT CGCTATGTC GCTATGTCG CTATGTCGA TATGTCGAT ATGTCGATA TGTCGATAA GTCGATAAC TCGATAACA CGATAACAA GATAACAAC ATAACAACT TAACAACTT AACAACTTC ACAACTTCT CAACTTCTG AACTTCTGT ACTTCTGTG CTTCTGTGG TTCTGTGGC TCTGTGGCC CTGTGGCCC TGTGGCCCT GTGGCCCTG TGGCCCTGA GGCCCTGAT GCCCTGATG CCCTGATGG CCTGATGGC CTGATGGCT TGATGGCTA GATGGCTAC ATGGCTACC TGGCTACCC GGCTACCCT GCTACCCTC CTACCCTCT TACCCTCTT ACCCTCTTG CCCTCTTGA CCTCTTGAG CTCTTGAGT TCTTGAGTG CTTGAGTGC TTGAGTGCA TGAGTGCAT GAGTGCATT AGTGCATTA GTGCATTAA TGCATTAAA GCATTAAAG CATTAAAGA ATTAAAGAC TTAAAGACC TAAAGACCT AAAGACCTT AAGACCTTC AGACCTTCT GACCTTCTA ACCTTCTAG CCTTCTAGC CTTCTAGCA TTCTAGCAC TCTAGCACG CTAGCACGT TAGCACGTG AGCACGTGC GCACGTGCT CACGTGCTG ACGTGCTGG CGTGCTGGT GTGCTGGTA TGCTGGTAA GCTGGTAAA CTGGTAAAG TGGTAAAGC GGTAAAGCT GTAAAGCTT TAAAGCTTC AAAGCTTCA AAGCTTCAT AGCTTCATG GCTTCATGC CTTCATGCA TTCATGCAC TCATGCACT CATGCACTT ATGCACTTT TGCACTTTG GCACTTTGT CACTTTGTC ACTTTGTCC CTTTGTCCG TTTGTCCGA TTGTCCGAA TGTCCGAAC GTCCGAACA TCCGAACAA CCGAACAAC CGAACAACT GAACAACTG AACAACTGG ACAACTGGA CAACTGGAC AACTGGACT ACTGGACTT CTGGACTTT TGGACTTTA GGACTTTAT GACTTTATT ACTTTATTG CTTTATTGA TTTATTGAC TTATTGACA TATTGACAC ATTGACACT TTGACACTA TGACACTAA GACACTAAG ACACTAAGA CACTAAGAG ACTAAGAGG CTAAGAGGG TAAGAGGGG AAGAGGGGT AGAGGGGTG GAGGGGTGT AGGGGTGTA GGGGTGTAT GGGTGTATA GGTGTATAC GTGTATACT TGTATACTG GTATACTGC TATACTGCT ATACTGCTG TACTGCTGC ACTGCTGCC CTGCTGCCG TGCTGCCGT GCTGCCGTG CTGCCGTGA TGCCGTGAA GCCGTGAAC CCGTGAACA CGTGAACAT GTGAACATG TGAACATGA GAACATGAG AACATGAGC ACATGAGCA CATGAGCAT ATGAGCATG TGAGCATGA GAGCATGAA AGCATGAAA GCATGAAAT CATGAAATT ATGAAATTG TGAAATTGC GAAATTGCT AAATTGCTT AATTGCTTG ATTGCTTGG TTGCTTGGT TGCTTGGTA GCTTGGTAC CTTGGTACA TTGGTACAC TGGTACACG GGTACACGG GTACACGGA TACACGGAA ACACGGAAC CACGGAACG ACGGAACGT CGGAACGTT GGAACGTTC GAACGTTCT AACGTTCTG ACGTTCTGA CGTTCTGAA GTTCTGAAA TTCTGAAAA TCTGAAAAG CTGAAAAGA TGAAAAGAG GAAAAGAGC AAAAGAGCT AAAGAGCTA AAGAGCTAT AGAGCTATG GAGCTATGA AGCTATGAA GCTATGAAT CTATGAATT TATGAATTG ATGAATTGC TGAATTGCA GAATTGCAG AATTGCAGA ATTGCAGAC TTGCAGACA TGCAGACAC GCAGACACC CAGACACCT AGACACCTT GACACCTTT ACACCTTTT CACCTTTTG ACCTTTTGA CCTTTTGAA CTTTTGAAA TTTTGAAAT TTTGAAATT TTGAAATTA TGAAATTAA GAAATTAAA AAATTAAAT AATTAAATT ATTAAATTG TTAAATTGG TAAATTGGC AAATTGGCA AATTGGCAA ATTGGCAAA TTGGCAAAG TGGCAAAGA GGCAAAGAA GCAAAGAAA CAAAGAAAT AAAGAAATT AAGAAATTT AGAAATTTG GAAATTTGA AAATTTGAC AATTTGACA ATTTGACAC TTTGACACC TTGACACCT TGACACCTT GACACCTTC ACACCTTCA CACCTTCAA ACCTTCAAT CCTTCAATG CTTCAATGG TTCAATGGG TCAATGGGG CAATGGGGA AATGGGGAA ATGGGGAAT TGGGGAATG GGGGAATGT GGGAATGTC GGAATGTCC GAATGTCCA AATGTCCAA ATGTCCAAA TGTCCAAAT GTCCAAATT TCCAAATTT CCAAATTTT CAAATTTTG AAATTTTGT AATTTTGTA ATTTTGTAT TTTTGTATT TTTGTATTT TTGTATTTC TGTATTTCC GTATTTCCC TATTTCCCT ATTTCCCTT TTTCCCTTA TTCCCTTAA TCCCTTAAA CCCTTAAAT CCTTAAATT CTTAAATTC TTAAATTCC TAAATTCCA AAATTCCAT AATTCCATA ATTCCATAA TTCCATAAT TCCATAATC CCATAATCA CATAATCAA ATAATCAAG TAATCAAGA AATCAAGAC ATCAAGACT TCAAGACTA CAAGACTAT AAGACTATT AGACTATTC GACTATTCA ACTATTCAA CTATTCAAC TATTCAACC ATTCAACCA TTCAACCAA TCAACCAAG CAACCAAGG AACCAAGGG ACCAAGGGT CCAAGGGTT CAAGGGTTG AAGGGTTGA AGGGTTGAA GGGTTGAAA GGTTGAAAA GTTGAAAAG TTGAAAAGA TGAAAAGAA GAAAAGAAA AAAAGAAAA AAAGAAAAA AAGAAAAAG AGAAAAAGC GAAAAAGCT AAAAAGCTT AAAAGCTTG AAAGCTTGA AAGCTTGAT AGCTTGATG GCTTGATGG CTTGATGGC TTGATGGCT TGATGGCTT GATGGCTTT ATGGCTTTA TGGCTTTAT GGCTTTATG GCTTTATGG CTTTATGGG TTTATGGGT TTATGGGTA TATGGGTAG ATGGGTAGA TGGGTAGAA GGGTAGAAT GGTAGAATT GTAGAATTC TAGAATTCG AGAATTCGA GAATTCGAT AATTCGATC ATTCGATCT TTCGATCTG TCGATCTGT CGATCTGTC GATCTGTCT ATCTGTCTA TCTGTCTAT CTGTCTATC TGTCTATCC GTCTATCCA TCTATCCAG CTATCCAGT TATCCAGTT ATCCAGTTG TCCAGTTGC CCAGTTGCG CAGTTGCGT AGTTGCGTC GTTGCGTCA TTGCGTCAC TGCGTCACC GCGTCACCA CGTCACCAA GTCACCAAA TCACCAAAT CACCAAATG ACCAAATGA CCAAATGAA CAAATGAAT AAATGAATG AATGAATGC ATGAATGCA TGAATGCAA GAATGCAAC AATGCAACC ATGCAACCA TGCAACCAA GCAACCAAA CAACCAAAT AACCAAATG ACCAAATGT CCAAATGTG CAAATGTGC AAATGTGCC AATGTGCCT ATGTGCCTT TGTGCCTTT GTGCCTTTC TGCCTTTCA GCCTTTCAA CCTTTCAAC CTTTCAACT TTTCAACTC TTCAACTCT TCAACTCTC CAACTCTCA AACTCTCAT ACTCTCATG CTCTCATGA TCTCATGAA CTCATGAAG TCATGAAGT CATGAAGTG ATGAAGTGT TGAAGTGTG GAAGTGTGA AAGTGTGAT AGTGTGATC GTGTGATCA TGTGATCAT GTGATCATT TGATCATTG GATCATTGT ATCATTGTG TCATTGTGG CATTGTGGT ATTGTGGTG TTGTGGTGA TGTGGTGAA GTGGTGAAA TGGTGAAAC GGTGAAACT GTGAAACTT TGAAACTTC GAAACTTCA AAACTTCAT AACTTCATG ACTTCATGG CTTCATGGC TTCATGGCA TCATGGCAG CATGGCAGA ATGGCAGAC TGGCAGACG GGCAGACGG GCAGACGGG CAGACGGGC AGACGGGCG GACGGGCGA ACGGGCGAT CGGGCGATT GGGCGATTT GGCGATTTT GCGATTTTG CGATTTTGT GATTTTGTT ATTTTGTTA TTTTGTTAA TTTGTTAAA TTGTTAAAG TGTTAAAGC GTTAAAGCC TTAAAGCCA TAAAGCCAC AAAGCCACT AAGCCACTT AGCCACTTG GCCACTTGC CCACTTGCG CACTTGCGA ACTTGCGAA CTTGCGAAT TTGCGAATT TGCGAATTT GCGAATTTT CGAATTTTG GAATTTTGT AATTTTGTG ATTTTGTGG TTTTGTGGC TTTGTGGCA TTGTGGCAC TGTGGCACT GTGGCACTG TGGCACTGA GGCACTGAG GCACTGAGA CACTGAGAA ACTGAGAAT CTGAGAATT TGAGAATTT GAGAATTTG AGAATTTGA GAATTTGAC AATTTGACT ATTTGACTA TTTGACTAA TTGACTAAA TGACTAAAG GACTAAAGA ACTAAAGAA CTAAAGAAG TAAAGAAGG AAAGAAGGT AAGAAGGTG AGAAGGTGC GAAGGTGCC AAGGTGCCA AGGTGCCAC GGTGCCACT GTGCCACTA TGCCACTAC GCCACTACT CCACTACTT CACTACTTG ACTACTTGT CTACTTGTG TACTTGTGG ACTTGTGGT CTTGTGGTT TTGTGGTTA TGTGGTTAC GTGGTTACT TGGTTACTT GGTTACTTA GTTACTTAC TTACTTACC TACTTACCC ACTTACCCC CTTACCCCA TTACCCCAA TACCCCAAA ACCCCAAAA CCCCAAAAT CCCAAAATG CCAAAATGC CAAAATGCT AAAATGCTG AAATGCTGT AATGCTGTT ATGCTGTTG TGCTGTTGT GCTGTTGTT CTGTTGTTA TGTTGTTAA GTTGTTAAA TTGTTAAAA TGTTAAAAT GTTAAAATT TTAAAATTT TAAAATTTA AAAATTTAT AAATTTATT AATTTATTG ATTTATTGT TTTATTGTC TTATTGTCC TATTGTCCA ATTGTCCAG TTGTCCAGC TGTCCAGCA GTCCAGCAT TCCAGCATG CCAGCATGT CAGCATGTC AGCATGTCA GCATGTCAC CATGTCACA ATGTCACAA TGTCACAAT GTCACAATT TCACAATTC CACAATTCA ACAATTCAG CAATTCAGA AATTCAGAA ATTCAGAAG TTCAGAAGT TCAGAAGTA CAGAAGTAG AGAAGTAGG GAAGTAGGA AAGTAGGAC AGTAGGACC GTAGGACCT TAGGACCTG AGGACCTGA GGACCTGAG GACCTGAGC ACCTGAGCA CCTGAGCAT CTGAGCATA TGAGCATAG GAGCATAGT AGCATAGTC GCATAGTCT CATAGTCTT ATAGTCTTG TAGTCTTGC AGTCTTGCC GTCTTGCCG TCTTGCCGA CTTGCCGAA TTGCCGAAT TGCCGAATA GCCGAATAC CCGAATACC CGAATACCA GAATACCAT AATACCATA ATACCATAA TACCATAAT ACCATAATG CCATAATGA CATAATGAA ATAATGAAT TAATGAATC AATGAATCT ATGAATCTG TGAATCTGG GAATCTGGC AATCTGGCT ATCTGGCTT TCTGGCTTG CTGGCTTGA TGGCTTGAA GGCTTGAAA GCTTGAAAA CTTGAAAAC TTGAAAACC TGAAAACCA GAAAACCAT AAAACCATT AAACCATTC AACCATTCT ACCATTCTT CCATTCTTC CATTCTTCG ATTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGG TCGTAAGGG CGTAAGGGT GTAAGGGTG TAAGGGTGG AAGGGTGGT AGGGTGGTC GGGTGGTCG GGTGGTCGC GTGGTCGCA TGGTCGCAC GGTCGCACT GTCGCACTA TCGCACTAT CGCACTATT GCACTATTG CACTATTGC ACTATTGCC CTATTGCCT TATTGCCTT ATTGCCTTT TTGCCTTTG TGCCTTTGG GCCTTTGGA CCTTTGGAG CTTTGGAGG TTTGGAGGC TTGGAGGCT TGGAGGCTG GGAGGCTGT GAGGCTGTG AGGCTGTGT GGCTGTGTG GCTGTGTGT CTGTGTGTT TGTGTGTTC GTGTGTTCT TGTGTTCTC GTGTTCTCT TGTTCTCTT GTTCTCTTA TTCTCTTAT TCTCTTATG CTCTTATGT TCTTATGTT CTTATGTTG TTATGTTGG TATGTTGGT ATGTTGGTT TGTTGGTTG GTTGGTTGC TTGGTTGCC TGGTTGCCA GGTTGCCAT GTTGCCATA TTGCCATAA TGCCATAAC GCCATAACA CCATAACAA CATAACAAG ATAACAAGT TAACAAGTG AACAAGTGT ACAAGTGTG CAAGTGTGC AAGTGTGCC AGTGTGCCT GTGTGCCTA TGTGCCTAT GTGCCTATT TGCCTATTG GCCTATTGG CCTATTGGG CTATTGGGT TATTGGGTT ATTGGGTTC TTGGGTTCC TGGGTTCCA GGGTTCCAC GGTTCCACG GTTCCACGT TTCCACGTG TCCACGTGC CCACGTGCT CACGTGCTA ACGTGCTAG CGTGCTAGC GTGCTAGCG TGCTAGCGC GCTAGCGCT CTAGCGCTA TAGCGCTAA AGCGCTAAC GCGCTAACA CGCTAACAT GCTAACATA CTAACATAG TAACATAGG AACATAGGT ACATAGGTT CATAGGTTG ATAGGTTGT TAGGTTGTA AGGTTGTAA GGTTGTAAC GTTGTAACC TTGTAACCA TGTAACCAT GTAACCATA TAACCATAC AACCATACA ACCATACAG CCATACAGG CATACAGGT ATACAGGTG TACAGGTGT ACAGGTGTT CAGGTGTTG AGGTGTTGT GGTGTTGTT GTGTTGTTG TGTTGTTGG GTTGTTGGA TTGTTGGAG TGTTGGAGA GTTGGAGAA TTGGAGAAG TGGAGAAGG GGAGAAGGT GAGAAGGTT AGAAGGTTC GAAGGTTCC AAGGTTCCG AGGTTCCGA GGTTCCGAA GTTCCGAAG TTCCGAAGG TCCGAAGGT CCGAAGGTC CGAAGGTCT GAAGGTCTT AAGGTCTTA AGGTCTTAA GGTCTTAAT GTCTTAATG TCTTAATGA CTTAATGAC TTAATGACA TAATGACAA AATGACAAC ATGACAACC TGACAACCT GACAACCTT ACAACCTTC CAACCTTCT AACCTTCTT ACCTTCTTG CCTTCTTGA CTTCTTGAA TTCTTGAAA TCTTGAAAT CTTGAAATA TTGAAATAC TGAAATACT GAAATACTC AAATACTCC AATACTCCA ATACTCCAA TACTCCAAA ACTCCAAAA CTCCAAAAA TCCAAAAAG CCAAAAAGA CAAAAAGAG AAAAAGAGA AAAAGAGAA AAAGAGAAA AAGAGAAAG AGAGAAAGT GAGAAAGTC AGAAAGTCA GAAAGTCAA AAAGTCAAC AAGTCAACA AGTCAACAT GTCAACATC TCAACATCA CAACATCAA AACATCAAT ACATCAATA CATCAATAT ATCAATATT TCAATATTG CAATATTGT AATATTGTT ATATTGTTG TATTGTTGG ATTGTTGGT TTGTTGGTG TGTTGGTGA GTTGGTGAC TTGGTGACT TGGTGACTT GGTGACTTT GTGACTTTA TGACTTTAA GACTTTAAA ACTTTAAAC CTTTAAACT TTTAAACTT TTAAACTTA TAAACTTAA AAACTTAAT AACTTAATG ACTTAATGA CTTAATGAA TTAATGAAG TAATGAAGA AATGAAGAG ATGAAGAGA TGAAGAGAT GAAGAGATC AAGAGATCG AGAGATCGC GAGATCGCC AGATCGCCA GATCGCCAT ATCGCCATT TCGCCATTA CGCCATTAT GCCATTATT CCATTATTT CATTATTTT ATTATTTTG TTATTTTGG TATTTTGGC ATTTTGGCA TTTTGGCAT TTTGGCATC TTGGCATCT TGGCATCTT GGCATCTTT GCATCTTTT CATCTTTTT ATCTTTTTC TCTTTTTCT CTTTTTCTG TTTTTCTGC TTTTCTGCT TTTCTGCTT TTCTGCTTC TCTGCTTCC CTGCTTCCA TGCTTCCAC GCTTCCACA CTTCCACAA TTCCACAAG TCCACAAGT CCACAAGTG CACAAGTGC ACAAGTGCT CAAGTGCTT AAGTGCTTT AGTGCTTTT GTGCTTTTG TGCTTTTGT GCTTTTGTG CTTTTGTGG TTTTGTGGA TTTGTGGAA TTGTGGAAA TGTGGAAAC GTGGAAACT TGGAAACTG GGAAACTGT GAAACTGTG AAACTGTGA AACTGTGAA ACTGTGAAA CTGTGAAAG TGTGAAAGG GTGAAAGGT TGAAAGGTT GAAAGGTTT AAAGGTTTG AAGGTTTGG AGGTTTGGA GGTTTGGAT GTTTGGATT TTTGGATTA TTGGATTAT TGGATTATA GGATTATAA GATTATAAA ATTATAAAG TTATAAAGC TATAAAGCA ATAAAGCAT TAAAGCATT AAAGCATTC AAGCATTCA AGCATTCAA GCATTCAAA CATTCAAAC ATTCAAACA TTCAAACAA TCAAACAAA CAAACAAAT AAACAAATT AACAAATTG ACAAATTGT CAAATTGTT AAATTGTTG AATTGTTGA ATTGTTGAA TTGTTGAAT TGTTGAATC GTTGAATCC TTGAATCCT TGAATCCTG GAATCCTGT AATCCTGTG ATCCTGTGG TCCTGTGGT CCTGTGGTA CTGTGGTAA TGTGGTAAT GTGGTAATT TGGTAATTT GGTAATTTT GTAATTTTA TAATTTTAA AATTTTAAA ATTTTAAAG TTTTAAAGT TTTAAAGTT TTAAAGTTA TAAAGTTAC AAAGTTACA AAGTTACAA AGTTACAAA GTTACAAAA TTACAAAAG TACAAAAGG ACAAAAGGA CAAAAGGAA AAAAGGAAA AAAGGAAAA AAGGAAAAG AGGAAAAGC GGAAAAGCT GAAAAGCTA AAAAGCTAA AAAGCTAAA AAGCTAAAA AGCTAAAAA GCTAAAAAA CTAAAAAAG TAAAAAAGG AAAAAAGGT AAAAAGGTG AAAAGGTGC AAAGGTGCC AAGGTGCCT AGGTGCCTG GGTGCCTGG GTGCCTGGA TGCCTGGAA GCCTGGAAT CCTGGAATA CTGGAATAT TGGAATATT GGAATATTG GAATATTGG AATATTGGT ATATTGGTG TATTGGTGA ATTGGTGAA TTGGTGAAC TGGTGAACA GGTGAACAG GTGAACAGA TGAACAGAA GAACAGAAA AACAGAAAT ACAGAAATC CAGAAATCA AGAAATCAA GAAATCAAT AAATCAATA AATCAATAC ATCAATACT TCAATACTG CAATACTGA AATACTGAG ATACTGAGT TACTGAGTC ACTGAGTCC CTGAGTCCT TGAGTCCTC GAGTCCTCT AGTCCTCTT GTCCTCTTT TCCTCTTTA CCTCTTTAT CTCTTTATG TCTTTATGC CTTTATGCA TTTATGCAT TTATGCATT TATGCATTT ATGCATTTG TGCATTTGC GCATTTGCA CATTTGCAT ATTTGCATC TTTGCATCA TTGCATCAG TGCATCAGA GCATCAGAG CATCAGAGG ATCAGAGGC TCAGAGGCT CAGAGGCTG AGAGGCTGC GAGGCTGCT AGGCTGCTC GGCTGCTCG GCTGCTCGT CTGCTCGTG TGCTCGTGT GCTCGTGTT CTCGTGTTG TCGTGTTGT CGTGTTGTA GTGTTGTAC TGTTGTACG GTTGTACGA TTGTACGAT TGTACGATC GTACGATCA TACGATCAA ACGATCAAT CGATCAATT GATCAATTT ATCAATTTT TCAATTTTC CAATTTTCT AATTTTCTC ATTTTCTCC TTTTCTCCC TTTCTCCCG TTCTCCCGC TCTCCCGCA CTCCCGCAC TCCCGCACT CCCGCACTC CCGCACTCT CGCACTCTT GCACTCTTG CACTCTTGA ACTCTTGAA CTCTTGAAA TCTTGAAAC CTTGAAACT TTGAAACTG TGAAACTGC GAAACTGCT AAACTGCTC AACTGCTCA ACTGCTCAA CTGCTCAAA TGCTCAAAA GCTCAAAAT CTCAAAATT TCAAAATTC CAAAATTCT AAAATTCTG AAATTCTGT AATTCTGTG ATTCTGTGC TTCTGTGCG TCTGTGCGT CTGTGCGTG TGTGCGTGT GTGCGTGTT TGCGTGTTT GCGTGTTTT CGTGTTTTA GTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGA TTTACAGAA TTACAGAAG TACAGAAGG ACAGAAGGC CAGAAGGCC AGAAGGCCG GAAGGCCGC AAGGCCGCT AGGCCGCTA GGCCGCTAT GCCGCTATA CCGCTATAA CGCTATAAC GCTATAACA CTATAACAA TATAACAAT ATAACAATA TAACAATAC AACAATACT ACAATACTA CAATACTAG AATACTAGA ATACTAGAT TACTAGATG ACTAGATGG CTAGATGGA TAGATGGAA AGATGGAAT GATGGAATT ATGGAATTT TGGAATTTC GGAATTTCA GAATTTCAC AATTTCACA ATTTCACAG TTTCACAGT TTCACAGTA TCACAGTAT CACAGTATT ACAGTATTC CAGTATTCA AGTATTCAC GTATTCACT TATTCACTG ATTCACTGA TTCACTGAG TCACTGAGA CACTGAGAC ACTGAGACT CTGAGACTC TGAGACTCA GAGACTCAT AGACTCATT 

In [ ]:
# Save k_mer_list in .txt file using json
PATH_files = "/content/drive/MyDrive/semantic_browser/COVID/" # k-mers path
with open(PATH_files + "try1_kmer_list.csv", "r") as fp:   #Serialize
  k_mer_list = json.load(fp)
print(len(k_mer_list))

2000

In [ ]:
PATH_files = "/content/drive/MyDrive/semantic_browser/COVID/"
#k_mer_list = []
filenames = []
for x in tqdm(file_list):
  #k_mer_aux = []
  filenames.append(folder_path + "/" + x)
  #with open(filename, "r") as fp:   # Unpickling
  #  k_mer_aux = json.load(fp)
  #k_mer_list.extend(k_mer_aux)
#with open(PATH_files + "complete_kmer_list.txt", "w") as fp:   #Serialize
#  json.dump(k_mer_list, fp)

100%|██████████| 90/90 [00:00<00:00, 21027.59it/s]

In [ ]:
print(len(filenames))
print(filenames[0])

90
/content/drive/MyDrive/semantic_browser/COVID/k_mers/999_kmer.txt

In [ ]:
kmer_path = "/content/drive/MyDrive/semantic_browser/COVID/complete_kmer_list.txt"
with open(kmer_path, "r") as fp:   # Unpickling
    kmer_list = json.load(fp)

In [ ]:
def read_txt_files(filename):
  """reads the k_mers files with json"""
  filename = folder_path + "/" + filename
  with open(filename, "r") as fp:   # Unpickling
    read_file = json.load(fp)
  k_mers = read_file
  return k_mers

def stack_list(iterable):
    """stack the k_mers in the iterable on a k_mer_list"""
    k_mer_list = []
    for item in iterable:
      k_mer_list += item
    return k_mer_list

def stack_using_generator(files):
  """iterate through a generator and stack the objects"""
  # notice the parentheses instead of square brackets in the next line 
  iterable = (read_txt_files(filename) for filename in tqdm(file_list[0:2]))
  k_mer_complete_list = stack_list(iterable)
  return k_mer_complete_list

k_mers = []
k_mer_list = stack_using_generator(k_mer_list)

# Save k_mer_list in .txt file using json
#PATH_files = "/content/drive/MyDrive/semantic_browser/COVID/" # k-mers path
#with open(PATH_files + "complete_kmer_list.txt", "w") as fp:   #Serialize
#  json.dump(k_mer_list, fp)

NameError: ignored

In [ ]:
PATH_files = "/content/drive/MyDrive/semantic_browser/COVID/"
k_mer_list = []
for x in tqdm(file_list[0:2]):
  k_mer_aux = []
  filename = folder_path + "/" + x
  with open(filename, "r") as fp:   # Unpickling
    k_mer_aux = json.load(fp)
  k_mer_list.extend(k_mer_aux)
#with open(PATH_files + "complete_kmer_list.txt", "w") as fp:   #Serialize
#  json.dump(k_mer_list, fp)
print(k_mer_list[0])

100%|██████████| 2/2 [00:03<00:00,  1.76s/it]

ATTAAAGGT TTAAAGGTT TAAAGGTTT AAAGGTTTA AAGGTTTAT AGGTTTATA GGTTTATAC GTTTATACC TTTATACCT TTATACCTT TATACCTTC ATACCTTCC TACCTTCCC ACCTTCCCA CCTTCCCAG CTTCCCAGG TTCCCAGGT TCCCAGGTA CCCAGGTAA CCAGGTAAC CAGGTAACA AGGTAACAA GGTAACAAA GTAACAAAC TAACAAACC AACAAACCA ACAAACCAA CAAACCAAC AAACCAACC AACCAACCA ACCAACCAA CCAACCAAC CAACCAACT AACCAACTT ACCAACTTT CCAACTTTC CAACTTTCG AACTTTCGA ACTTTCGAT CTTTCGATC TTTCGATCT TTCGATCTC TCGATCTCT CGATCTCTT GATCTCTTG ATCTCTTGT TCTCTTGTA CTCTTGTAG TCTTGTAGA CTTGTAGAT TTGTAGATC TGTAGATCT GTAGATCTG TAGATCTGT AGATCTGTT GATCTGTTC ATCTGTTCT TCTGTTCTC CTGTTCTCT TGTTCTCTA GTTCTCTAA TTCTCTAAA TCTCTAAAC CTCTAAACG TCTAAACGA CTAAACGAA TAAACGAAC AAACGAACT AACGAACTT ACGAACTTT CGAACTTTA GAACTTTAA AACTTTAAA ACTTTAAAA CTTTAAAAT TTTAAAATC TTAAAATCT TAAAATCTG AAAATCTGT AAATCTGTG AATCTGTGT ATCTGTGTG TCTGTGTGG CTGTGTGGC TGTGTGGCT GTGTGGCTG TGTGGCTGT GTGGCTGTC TGGCTGTCA GGCTGTCAC GCTGTCACT CTGTCACTC TGTCACTCG GTCACTCGG TCACTCGGC CACTCGGCT ACTCGGCTG CTCGGCTGC TCGGCTGCA CGGCTGCAT GGCTGCATG GCTGCATGC CTGCATGCT TGCATGCTT GCATGCTTA CATGCTTAG ATGCTTAGT TGCTTAGTG GCTTAGTGC CTTAGTGCA TTAGTGCAC TAGTGCACT AGTGCACTC GTGCACTCA TGCACTCAC GCACTCACG CACTCACGC ACTCACGCA CTCACGCAG TCACGCAGT CACGCAGTA ACGCAGTAT CGCAGTATA GCAGTATAA CAGTATAAT AGTATAATT GTATAATTA TATAATTAA ATAATTAAT TAATTAATA AATTAATAA ATTAATAAC TTAATAACT TAATAACTA AATAACTAA ATAACTAAT TAACTAATT AACTAATTA ACTAATTAC CTAATTACT TAATTACTG AATTACTGT ATTACTGTC TTACTGTCG TACTGTCGT ACTGTCGTT CTGTCGTTG TGTCGTTGA GTCGTTGAC TCGTTGACA CGTTGACAG GTTGACAGG TTGACAGGA TGACAGGAC GACAGGACA ACAGGACAC CAGGACACG AGGACACGA GGACACGAG GACACGAGT ACACGAGTA CACGAGTAA ACGAGTAAC CGAGTAACT GAGTAACTC AGTAACTCG GTAACTCGT TAACTCGTC AACTCGTCT ACTCGTCTA CTCGTCTAT TCGTCTATC CGTCTATCT GTCTATCTT TCTATCTTC CTATCTTCT TATCTTCTG ATCTTCTGC TCTTCTGCA CTTCTGCAG TTCTGCAGG TCTGCAGGC CTGCAGGCT TGCAGGCTG GCAGGCTGC CAGGCTGCT AGGCTGCTT GGCTGCTTA GCTGCTTAC CTGCTTACG TGCTTACGG GCTTACGGT CTTACGGTT TTACGGTTT TACGGTTTC ACGGTTTCG CGGTTTCGT GGTTTCGTC GTTTCGTCC TTTCGTCCG TTCGTCCGT TCGTCCGTG CGTCCGTGT GTCCGTGTT TCCGTGTTG CCGTGTTGC CGTGTTGCA GTGTTGCAG TGTTGCAGC GTTGCAGCC TTGCAGCCG TGCAGCCGA GCAGCCGAT CAGCCGATC AGCCGATCA GCCGATCAT CCGATCATC CGATCATCA GATCATCAG ATCATCAGC TCATCAGCA CATCAGCAC ATCAGCACA TCAGCACAT CAGCACATC AGCACATCT GCACATCTA CACATCTAG ACATCTAGG CATCTAGGT ATCTAGGTT TCTAGGTTT CTAGGTTTT TAGGTTTTG AGGTTTTGT GGTTTTGTC GTTTTGTCC TTTTGTCCG TTTGTCCGG TTGTCCGGG TGTCCGGGT GTCCGGGTG TCCGGGTGT CCGGGTGTG CGGGTGTGA GGGTGTGAC GGTGTGACC GTGTGACCG TGTGACCGA GTGACCGAA TGACCGAAA GACCGAAAG ACCGAAAGG CCGAAAGGT CGAAAGGTA GAAAGGTAA AAAGGTAAG AAGGTAAGA AGGTAAGAT GGTAAGATG GTAAGATGG TAAGATGGA AAGATGGAG AGATGGAGA GATGGAGAG ATGGAGAGC TGGAGAGCC GGAGAGCCT GAGAGCCTT AGAGCCTTG GAGCCTTGT AGCCTTGTC GCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTG TGTCCCTGG GTCCCTGGT TCCCTGGTT CCCTGGTTT CCTGGTTTC CTGGTTTCA TGGTTTCAA GGTTTCAAC GTTTCAACG TTTCAACGA TTCAACGAG TCAACGAGA CAACGAGAA AACGAGAAA ACGAGAAAA CGAGAAAAC GAGAAAACA AGAAAACAC GAAAACACA AAAACACAC AAACACACG AACACACGT ACACACGTC CACACGTCC ACACGTCCA CACGTCCAA ACGTCCAAC CGTCCAACT GTCCAACTC TCCAACTCA CCAACTCAG CAACTCAGT AACTCAGTT ACTCAGTTT CTCAGTTTG TCAGTTTGC CAGTTTGCC AGTTTGCCT GTTTGCCTG TTTGCCTGT TTGCCTGTT TGCCTGTTT GCCTGTTTT CCTGTTTTA CTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGG TTTACAGGT TTACAGGTT TACAGGTTC ACAGGTTCG CAGGTTCGC AGGTTCGCG GGTTCGCGA GTTCGCGAC TTCGCGACG TCGCGACGT CGCGACGTG GCGACGTGC CGACGTGCT GACGTGCTC ACGTGCTCG CGTGCTCGT GTGCTCGTA TGCTCGTAC GCTCGTACG CTCGTACGT TCGTACGTG CGTACGTGG GTACGTGGC TACGTGGCT ACGTGGCTT CGTGGCTTT GTGGCTTTG TGGCTTTGG GGCTTTGGA GCTTTGGAG CTTTGGAGA TTTGGAGAC TTGGAGACT TGGAGACTC GGAGACTCC GAGACTCCG AGACTCCGT GACTCCGTG ACTCCGTGG CTCCGTGGA TCCGTGGAG CCGTGGAGG CGTGGAGGA GTGGAGGAG TGGAGGAGG GGAGGAGGT GAGGAGGTC AGGAGGTCT GGAGGTCTT GAGGTCTTA AGGTCTTAT GGTCTTATC GTCTTATCA TCTTATCAG CTTATCAGA TTATCAGAG TATCAGAGG ATCAGAGGC TCAGAGGCA CAGAGGCAC AGAGGCACG GAGGCACGT AGGCACGTC GGCACGTCA GCACGTCAA CACGTCAAC ACGTCAACA CGTCAACAT GTCAACATC TCAACATCT CAACATCTT AACATCTTA ACATCTTAA CATCTTAAA ATCTTAAAG TCTTAAAGA CTTAAAGAT TTAAAGATG TAAAGATGG AAAGATGGC AAGATGGCA AGATGGCAC GATGGCACT ATGGCACTT TGGCACTTG GGCACTTGT GCACTTGTG CACTTGTGG ACTTGTGGC CTTGTGGCT TTGTGGCTT TGTGGCTTA GTGGCTTAG TGGCTTAGT GGCTTAGTA GCTTAGTAG CTTAGTAGA TTAGTAGAA TAGTAGAAG AGTAGAAGT GTAGAAGTT TAGAAGTTG AGAAGTTGA GAAGTTGAA AAGTTGAAA AGTTGAAAA GTTGAAAAA TTGAAAAAG TGAAAAAGG GAAAAAGGC AAAAAGGCG AAAAGGCGT AAAGGCGTT AAGGCGTTT AGGCGTTTT GGCGTTTTG GCGTTTTGC CGTTTTGCC GTTTTGCCT TTTTGCCTC TTTGCCTCA TTGCCTCAA TGCCTCAAC GCCTCAACT CCTCAACTT CTCAACTTG TCAACTTGA CAACTTGAA AACTTGAAC ACTTGAACA CTTGAACAG TTGAACAGC TGAACAGCC GAACAGCCC AACAGCCCT ACAGCCCTA CAGCCCTAT AGCCCTATG GCCCTATGT CCCTATGTG CCTATGTGT CTATGTGTT TATGTGTTC ATGTGTTCA TGTGTTCAT GTGTTCATC TGTTCATCA GTTCATCAA TTCATCAAA TCATCAAAC CATCAAACG ATCAAACGT TCAAACGTT CAAACGTTC AAACGTTCG AACGTTCGG ACGTTCGGA CGTTCGGAT GTTCGGATG TTCGGATGC TCGGATGCT CGGATGCTC GGATGCTCG GATGCTCGA ATGCTCGAA TGCTCGAAC GCTCGAACT CTCGAACTG TCGAACTGC CGAACTGCA GAACTGCAC AACTGCACC ACTGCACCT CTGCACCTC TGCACCTCA GCACCTCAT CACCTCATG ACCTCATGG CCTCATGGT CTCATGGTC TCATGGTCA CATGGTCAT ATGGTCATG TGGTCATGT GGTCATGTT GTCATGTTA TCATGTTAT CATGTTATG ATGTTATGG TGTTATGGT GTTATGGTT TTATGGTTG TATGGTTGA ATGGTTGAG TGGTTGAGC GGTTGAGCT GTTGAGCTG TTGAGCTGG TGAGCTGGT GAGCTGGTA AGCTGGTAG GCTGGTAGC CTGGTAGCA TGGTAGCAG GGTAGCAGA GTAGCAGAA TAGCAGAAC AGCAGAACT GCAGAACTC CAGAACTCG AGAACTCGA GAACTCGAA AACTCGAAG ACTCGAAGG CTCGAAGGC TCGAAGGCA CGAAGGCAT GAAGGCATT AAGGCATTC AGGCATTCA GGCATTCAG GCATTCAGT CATTCAGTA ATTCAGTAC TTCAGTACG TCAGTACGG CAGTACGGT AGTACGGTC GTACGGTCG TACGGTCGT ACGGTCGTA CGGTCGTAG GGTCGTAGT GTCGTAGTG TCGTAGTGG CGTAGTGGT GTAGTGGTG TAGTGGTGA AGTGGTGAG GTGGTGAGA TGGTGAGAC GGTGAGACA GTGAGACAC TGAGACACT GAGACACTT AGACACTTG GACACTTGG ACACTTGGT CACTTGGTG ACTTGGTGT CTTGGTGTC TTGGTGTCC TGGTGTCCT GGTGTCCTT GTGTCCTTG TGTCCTTGT GTCCTTGTC TCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTC TGTCCCTCA GTCCCTCAT TCCCTCATG CCCTCATGT CCTCATGTG CTCATGTGG TCATGTGGG CATGTGGGC ATGTGGGCG TGTGGGCGA GTGGGCGAA TGGGCGAAA GGGCGAAAT GGCGAAATA GCGAAATAC CGAAATACC GAAATACCA AAATACCAG AATACCAGT ATACCAGTG TACCAGTGG ACCAGTGGC CCAGTGGCT CAGTGGCTT AGTGGCTTA GTGGCTTAC TGGCTTACC GGCTTACCG GCTTACCGC CTTACCGCA TTACCGCAA TACCGCAAG ACCGCAAGG CCGCAAGGT CGCAAGGTT GCAAGGTTC CAAGGTTCT AAGGTTCTT AGGTTCTTC GGTTCTTCT GTTCTTCTT TTCTTCTTC TCTTCTTCG CTTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGA TCGTAAGAA CGTAAGAAC GTAAGAACG TAAGAACGG AAGAACGGT AGAACGGTA GAACGGTAA AACGGTAAT ACGGTAATA CGGTAATAA GGTAATAAA GTAATAAAG TAATAAAGG AATAAAGGA ATAAAGGAG TAAAGGAGC AAAGGAGCT AAGGAGCTG AGGAGCTGG GGAGCTGGT GAGCTGGTG AGCTGGTGG GCTGGTGGC CTGGTGGCC TGGTGGCCA GGTGGCCAT GTGGCCATA TGGCCATAG GGCCATAGT GCCATAGTT CCATAGTTA CATAGTTAC ATAGTTACG TAGTTACGG AGTTACGGC GTTACGGCG TTACGGCGC TACGGCGCC ACGGCGCCG CGGCGCCGA GGCGCCGAT GCGCCGATC CGCCGATCT GCCGATCTA CCGATCTAA CGATCTAAA GATCTAAAG ATCTAAAGT TCTAAAGTC CTAAAGTCA TAAAGTCAT AAAGTCATT AAGTCATTT AGTCATTTG GTCATTTGA TCATTTGAC CATTTGACT ATTTGACTT TTTGACTTA TTGACTTAG TGACTTAGG GACTTAGGC ACTTAGGCG CTTAGGCGA TTAGGCGAC TAGGCGACG AGGCGACGA GGCGACGAG GCGACGAGC CGACGAGCT GACGAGCTT ACGAGCTTG CGAGCTTGG GAGCTTGGC AGCTTGGCA GCTTGGCAC CTTGGCACT TTGGCACTG TGGCACTGA GGCACTGAT GCACTGATC CACTGATCC ACTGATCCT CTGATCCTT TGATCCTTA GATCCTTAT ATCCTTATG TCCTTATGA CCTTATGAA CTTATGAAG TTATGAAGA TATGAAGAT ATGAAGATT TGAAGATTT GAAGATTTT AAGATTTTC AGATTTTCA GATTTTCAA ATTTTCAAG TTTTCAAGA TTTCAAGAA TTCAAGAAA TCAAGAAAA CAAGAAAAC AAGAAAACT AGAAAACTG GAAAACTGG AAAACTGGA AAACTGGAA AACTGGAAC ACTGGAACA CTGGAACAC TGGAACACT GGAACACTA GAACACTAA AACACTAAA ACACTAAAC CACTAAACA ACTAAACAT CTAAACATA TAAACATAG AAACATAGC AACATAGCA ACATAGCAG CATAGCAGT ATAGCAGTG TAGCAGTGG AGCAGTGGT GCAGTGGTG CAGTGGTGT AGTGGTGTT GTGGTGTTA TGGTGTTAC GGTGTTACC GTGTTACCC TGTTACCCG GTTACCCGT TTACCCGTG TACCCGTGA ACCCGTGAA CCCGTGAAC CCGTGAACT CGTGAACTC GTGAACTCA TGAACTCAT GAACTCATG AACTCATGC ACTCATGCG CTCATGCGT TCATGCGTG CATGCGTGA ATGCGTGAG TGCGTGAGC GCGTGAGCT CGTGAGCTT GTGAGCTTA TGAGCTTAA GAGCTTAAC AGCTTAACG GCTTAACGG CTTAACGGA TTAACGGAG TAACGGAGG AACGGAGGG ACGGAGGGG CGGAGGGGC GGAGGGGCA GAGGGGCAT AGGGGCATA GGGGCATAC GGGCATACA GGCATACAC GCATACACT CATACACTC ATACACTCG TACACTCGC ACACTCGCT CACTCGCTA ACTCGCTAT CTCGCTATG TCGCTATGT CGCTATGTC GCTATGTCG CTATGTCGA TATGTCGAT ATGTCGATA TGTCGATAA GTCGATAAC TCGATAACA CGATAACAA GATAACAAC ATAACAACT TAACAACTT AACAACTTC ACAACTTCT CAACTTCTG AACTTCTGT ACTTCTGTG CTTCTGTGG TTCTGTGGC TCTGTGGCC CTGTGGCCC TGTGGCCCT GTGGCCCTG TGGCCCTGA GGCCCTGAT GCCCTGATG CCCTGATGG CCTGATGGC CTGATGGCT TGATGGCTA GATGGCTAC ATGGCTACC TGGCTACCC GGCTACCCT GCTACCCTC CTACCCTCT TACCCTCTT ACCCTCTTG CCCTCTTGA CCTCTTGAG CTCTTGAGT TCTTGAGTG CTTGAGTGC TTGAGTGCA TGAGTGCAT GAGTGCATT AGTGCATTA GTGCATTAA TGCATTAAA GCATTAAAG CATTAAAGA ATTAAAGAC TTAAAGACC TAAAGACCT AAAGACCTT AAGACCTTC AGACCTTCT GACCTTCTA ACCTTCTAG CCTTCTAGC CTTCTAGCA TTCTAGCAC TCTAGCACG CTAGCACGT TAGCACGTG AGCACGTGC GCACGTGCT CACGTGCTG ACGTGCTGG CGTGCTGGT GTGCTGGTA TGCTGGTAA GCTGGTAAA CTGGTAAAG TGGTAAAGC GGTAAAGCT GTAAAGCTT TAAAGCTTC AAAGCTTCA AAGCTTCAT AGCTTCATG GCTTCATGC CTTCATGCA TTCATGCAC TCATGCACT CATGCACTT ATGCACTTT TGCACTTTG GCACTTTGT CACTTTGTC ACTTTGTCC CTTTGTCCG TTTGTCCGA TTGTCCGAA TGTCCGAAC GTCCGAACA TCCGAACAA CCGAACAAC CGAACAACT GAACAACTG AACAACTGG ACAACTGGA CAACTGGAC AACTGGACT ACTGGACTT CTGGACTTT TGGACTTTA GGACTTTAT GACTTTATT ACTTTATTG CTTTATTGA TTTATTGAC TTATTGACA TATTGACAC ATTGACACT TTGACACTA TGACACTAA GACACTAAG ACACTAAGA CACTAAGAG ACTAAGAGG CTAAGAGGG TAAGAGGGG AAGAGGGGT AGAGGGGTG GAGGGGTGT AGGGGTGTA GGGGTGTAT GGGTGTATA GGTGTATAC GTGTATACT TGTATACTG GTATACTGC TATACTGCT ATACTGCTG TACTGCTGC ACTGCTGCC CTGCTGCCG TGCTGCCGT GCTGCCGTG CTGCCGTGA TGCCGTGAA GCCGTGAAC CCGTGAACA CGTGAACAT GTGAACATG TGAACATGA GAACATGAG AACATGAGC ACATGAGCA CATGAGCAT ATGAGCATG TGAGCATGA GAGCATGAA AGCATGAAA GCATGAAAT CATGAAATT ATGAAATTG TGAAATTGC GAAATTGCT AAATTGCTT AATTGCTTG ATTGCTTGG TTGCTTGGT TGCTTGGTA GCTTGGTAC CTTGGTACA TTGGTACAC TGGTACACG GGTACACGG GTACACGGA TACACGGAA ACACGGAAC CACGGAACG ACGGAACGT CGGAACGTT GGAACGTTC GAACGTTCT AACGTTCTG ACGTTCTGA CGTTCTGAA GTTCTGAAA TTCTGAAAA TCTGAAAAG CTGAAAAGA TGAAAAGAG GAAAAGAGC AAAAGAGCT AAAGAGCTA AAGAGCTAT AGAGCTATG GAGCTATGA AGCTATGAA GCTATGAAT CTATGAATT TATGAATTG ATGAATTGC TGAATTGCA GAATTGCAG AATTGCAGA ATTGCAGAC TTGCAGACA TGCAGACAC GCAGACACC CAGACACCT AGACACCTT GACACCTTT ACACCTTTT CACCTTTTG ACCTTTTGA CCTTTTGAA CTTTTGAAA TTTTGAAAT TTTGAAATT TTGAAATTA TGAAATTAA GAAATTAAA AAATTAAAT AATTAAATT ATTAAATTG TTAAATTGG TAAATTGGC AAATTGGCA AATTGGCAA ATTGGCAAA TTGGCAAAG TGGCAAAGA GGCAAAGAA GCAAAGAAA CAAAGAAAT AAAGAAATT AAGAAATTT AGAAATTTG GAAATTTGA AAATTTGAC AATTTGACA ATTTGACAC TTTGACACC TTGACACCT TGACACCTT GACACCTTC ACACCTTCA CACCTTCAA ACCTTCAAT CCTTCAATG CTTCAATGG TTCAATGGG TCAATGGGG CAATGGGGA AATGGGGAA ATGGGGAAT TGGGGAATG GGGGAATGT GGGAATGTC GGAATGTCC GAATGTCCA AATGTCCAA ATGTCCAAA TGTCCAAAT GTCCAAATT TCCAAATTT CCAAATTTT CAAATTTTG AAATTTTGT AATTTTGTA ATTTTGTAT TTTTGTATT TTTGTATTT TTGTATTTC TGTATTTCC GTATTTCCC TATTTCCCT ATTTCCCTT TTTCCCTTA TTCCCTTAA TCCCTTAAA CCCTTAAAT CCTTAAATT CTTAAATTC TTAAATTCC TAAATTCCA AAATTCCAT AATTCCATA ATTCCATAA TTCCATAAT TCCATAATC CCATAATCA CATAATCAA ATAATCAAG TAATCAAGA AATCAAGAC ATCAAGACT TCAAGACTA CAAGACTAT AAGACTATT AGACTATTC GACTATTCA ACTATTCAA CTATTCAAC TATTCAACC ATTCAACCA TTCAACCAA TCAACCAAG CAACCAAGG AACCAAGGG ACCAAGGGT CCAAGGGTT CAAGGGTTG AAGGGTTGA AGGGTTGAA GGGTTGAAA GGTTGAAAA GTTGAAAAG TTGAAAAGA TGAAAAGAA GAAAAGAAA AAAAGAAAA AAAGAAAAA AAGAAAAAG AGAAAAAGC GAAAAAGCT AAAAAGCTT AAAAGCTTG AAAGCTTGA AAGCTTGAT AGCTTGATG GCTTGATGG CTTGATGGC TTGATGGCT TGATGGCTT GATGGCTTT ATGGCTTTA TGGCTTTAT GGCTTTATG GCTTTATGG CTTTATGGG TTTATGGGT TTATGGGTA TATGGGTAG ATGGGTAGA TGGGTAGAA GGGTAGAAT GGTAGAATT GTAGAATTC TAGAATTCG AGAATTCGA GAATTCGAT AATTCGATC ATTCGATCT TTCGATCTG TCGATCTGT CGATCTGTC GATCTGTCT ATCTGTCTA TCTGTCTAT CTGTCTATC TGTCTATCC GTCTATCCA TCTATCCAG CTATCCAGT TATCCAGTT ATCCAGTTG TCCAGTTGC CCAGTTGCG CAGTTGCGT AGTTGCGTC GTTGCGTCA TTGCGTCAC TGCGTCACC GCGTCACCA CGTCACCAA GTCACCAAA TCACCAAAT CACCAAATG ACCAAATGA CCAAATGAA CAAATGAAT AAATGAATG AATGAATGC ATGAATGCA TGAATGCAA GAATGCAAC AATGCAACC ATGCAACCA TGCAACCAA GCAACCAAA CAACCAAAT AACCAAATG ACCAAATGT CCAAATGTG CAAATGTGC AAATGTGCC AATGTGCCT ATGTGCCTT TGTGCCTTT GTGCCTTTC TGCCTTTCA GCCTTTCAA CCTTTCAAC CTTTCAACT TTTCAACTC TTCAACTCT TCAACTCTC CAACTCTCA AACTCTCAT ACTCTCATG CTCTCATGA TCTCATGAA CTCATGAAG TCATGAAGT CATGAAGTG ATGAAGTGT TGAAGTGTG GAAGTGTGA AAGTGTGAT AGTGTGATC GTGTGATCA TGTGATCAT GTGATCATT TGATCATTG GATCATTGT ATCATTGTG TCATTGTGG CATTGTGGT ATTGTGGTG TTGTGGTGA TGTGGTGAA GTGGTGAAA TGGTGAAAC GGTGAAACT GTGAAACTT TGAAACTTC GAAACTTCA AAACTTCAT AACTTCATG ACTTCATGG CTTCATGGC TTCATGGCA TCATGGCAG CATGGCAGA ATGGCAGAC TGGCAGACG GGCAGACGG GCAGACGGG CAGACGGGC AGACGGGCG GACGGGCGA ACGGGCGAT CGGGCGATT GGGCGATTT GGCGATTTT GCGATTTTG CGATTTTGT GATTTTGTT ATTTTGTTA TTTTGTTAA TTTGTTAAA TTGTTAAAG TGTTAAAGC GTTAAAGCC TTAAAGCCA TAAAGCCAC AAAGCCACT AAGCCACTT AGCCACTTG GCCACTTGC CCACTTGCG CACTTGCGA ACTTGCGAA CTTGCGAAT TTGCGAATT TGCGAATTT GCGAATTTT CGAATTTTG GAATTTTGT AATTTTGTG ATTTTGTGG TTTTGTGGC TTTGTGGCA TTGTGGCAC TGTGGCACT GTGGCACTG TGGCACTGA GGCACTGAG GCACTGAGA CACTGAGAA ACTGAGAAT CTGAGAATT TGAGAATTT GAGAATTTG AGAATTTGA GAATTTGAC AATTTGACT ATTTGACTA TTTGACTAA TTGACTAAA TGACTAAAG GACTAAAGA ACTAAAGAA CTAAAGAAG TAAAGAAGG AAAGAAGGT AAGAAGGTG AGAAGGTGC GAAGGTGCC AAGGTGCCA AGGTGCCAC GGTGCCACT GTGCCACTA TGCCACTAC GCCACTACT CCACTACTT CACTACTTG ACTACTTGT CTACTTGTG TACTTGTGG ACTTGTGGT CTTGTGGTT TTGTGGTTA TGTGGTTAC GTGGTTACT TGGTTACTT GGTTACTTA GTTACTTAC TTACTTACC TACTTACCC ACTTACCCC CTTACCCCA TTACCCCAA TACCCCAAA ACCCCAAAA CCCCAAAAT CCCAAAATG CCAAAATGC CAAAATGCT AAAATGCTG AAATGCTGT AATGCTGTT ATGCTGTTG TGCTGTTGT GCTGTTGTT CTGTTGTTA TGTTGTTAA GTTGTTAAA TTGTTAAAA TGTTAAAAT GTTAAAATT TTAAAATTT TAAAATTTA AAAATTTAT AAATTTATT AATTTATTG ATTTATTGT TTTATTGTC TTATTGTCC TATTGTCCA ATTGTCCAG TTGTCCAGC TGTCCAGCA GTCCAGCAT TCCAGCATG CCAGCATGT CAGCATGTC AGCATGTCA GCATGTCAC CATGTCACA ATGTCACAA TGTCACAAT GTCACAATT TCACAATTC CACAATTCA ACAATTCAG CAATTCAGA AATTCAGAA ATTCAGAAG TTCAGAAGT TCAGAAGTA CAGAAGTAG AGAAGTAGG GAAGTAGGA AAGTAGGAC AGTAGGACC GTAGGACCT TAGGACCTG AGGACCTGA GGACCTGAG GACCTGAGC ACCTGAGCA CCTGAGCAT CTGAGCATA TGAGCATAG GAGCATAGT AGCATAGTC GCATAGTCT CATAGTCTT ATAGTCTTG TAGTCTTGC AGTCTTGCC GTCTTGCCG TCTTGCCGA CTTGCCGAA TTGCCGAAT TGCCGAATA GCCGAATAC CCGAATACC CGAATACCA GAATACCAT AATACCATA ATACCATAA TACCATAAT ACCATAATG CCATAATGA CATAATGAA ATAATGAAT TAATGAATC AATGAATCT ATGAATCTG TGAATCTGG GAATCTGGC AATCTGGCT ATCTGGCTT TCTGGCTTG CTGGCTTGA TGGCTTGAA GGCTTGAAA GCTTGAAAA CTTGAAAAC TTGAAAACC TGAAAACCA GAAAACCAT AAAACCATT AAACCATTC AACCATTCT ACCATTCTT CCATTCTTC CATTCTTCG ATTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGG TCGTAAGGG CGTAAGGGT GTAAGGGTG TAAGGGTGG AAGGGTGGT AGGGTGGTC GGGTGGTCG GGTGGTCGC GTGGTCGCA TGGTCGCAC GGTCGCACT GTCGCACTA TCGCACTAT CGCACTATT GCACTATTG CACTATTGC ACTATTGCC CTATTGCCT TATTGCCTT ATTGCCTTT TTGCCTTTG TGCCTTTGG GCCTTTGGA CCTTTGGAG CTTTGGAGG TTTGGAGGC TTGGAGGCT TGGAGGCTG GGAGGCTGT GAGGCTGTG AGGCTGTGT GGCTGTGTG GCTGTGTGT CTGTGTGTT TGTGTGTTC GTGTGTTCT TGTGTTCTC GTGTTCTCT TGTTCTCTT GTTCTCTTA TTCTCTTAT TCTCTTATG CTCTTATGT TCTTATGTT CTTATGTTG TTATGTTGG TATGTTGGT ATGTTGGTT TGTTGGTTG GTTGGTTGC TTGGTTGCC TGGTTGCCA GGTTGCCAT GTTGCCATA TTGCCATAA TGCCATAAC GCCATAACA CCATAACAA CATAACAAG ATAACAAGT TAACAAGTG AACAAGTGT ACAAGTGTG CAAGTGTGC AAGTGTGCC AGTGTGCCT GTGTGCCTA TGTGCCTAT GTGCCTATT TGCCTATTG GCCTATTGG CCTATTGGG CTATTGGGT TATTGGGTT ATTGGGTTC TTGGGTTCC TGGGTTCCA GGGTTCCAC GGTTCCACG GTTCCACGT TTCCACGTG TCCACGTGC CCACGTGCT CACGTGCTA ACGTGCTAG CGTGCTAGC GTGCTAGCG TGCTAGCGC GCTAGCGCT CTAGCGCTA TAGCGCTAA AGCGCTAAC GCGCTAACA CGCTAACAT GCTAACATA CTAACATAG TAACATAGG AACATAGGT ACATAGGTT CATAGGTTG ATAGGTTGT TAGGTTGTA AGGTTGTAA GGTTGTAAC GTTGTAACC TTGTAACCA TGTAACCAT GTAACCATA TAACCATAC AACCATACA ACCATACAG CCATACAGG CATACAGGT ATACAGGTG TACAGGTGT ACAGGTGTT CAGGTGTTG AGGTGTTGT GGTGTTGTT GTGTTGTTG TGTTGTTGG GTTGTTGGA TTGTTGGAG TGTTGGAGA GTTGGAGAA TTGGAGAAG TGGAGAAGG GGAGAAGGT GAGAAGGTT AGAAGGTTC GAAGGTTCC AAGGTTCCG AGGTTCCGA GGTTCCGAA GTTCCGAAG TTCCGAAGG TCCGAAGGT CCGAAGGTC CGAAGGTCT GAAGGTCTT AAGGTCTTA AGGTCTTAA GGTCTTAAT GTCTTAATG TCTTAATGA CTTAATGAC TTAATGACA TAATGACAA AATGACAAC ATGACAACC TGACAACCT GACAACCTT ACAACCTTC CAACCTTCT AACCTTCTT ACCTTCTTG CCTTCTTGA CTTCTTGAA TTCTTGAAA TCTTGAAAT CTTGAAATA TTGAAATAC TGAAATACT GAAATACTC AAATACTCC AATACTCCA ATACTCCAA TACTCCAAA ACTCCAAAA CTCCAAAAA TCCAAAAAG CCAAAAAGA CAAAAAGAG AAAAAGAGA AAAAGAGAA AAAGAGAAA AAGAGAAAG AGAGAAAGT GAGAAAGTC AGAAAGTCA GAAAGTCAA AAAGTCAAC AAGTCAACA AGTCAACAT GTCAACATC TCAACATCA CAACATCAA AACATCAAT ACATCAATA CATCAATAT ATCAATATT TCAATATTG CAATATTGT AATATTGTT ATATTGTTG TATTGTTGG ATTGTTGGT TTGTTGGTG TGTTGGTGA GTTGGTGAC TTGGTGACT TGGTGACTT GGTGACTTT GTGACTTTA TGACTTTAA GACTTTAAA ACTTTAAAC CTTTAAACT TTTAAACTT TTAAACTTA TAAACTTAA AAACTTAAT AACTTAATG ACTTAATGA CTTAATGAA TTAATGAAG TAATGAAGA AATGAAGAG ATGAAGAGA TGAAGAGAT GAAGAGATC AAGAGATCG AGAGATCGC GAGATCGCC AGATCGCCA GATCGCCAT ATCGCCATT TCGCCATTA CGCCATTAT GCCATTATT CCATTATTT CATTATTTT ATTATTTTG TTATTTTGG TATTTTGGC ATTTTGGCA TTTTGGCAT TTTGGCATC TTGGCATCT TGGCATCTT GGCATCTTT GCATCTTTT CATCTTTTT ATCTTTTTC TCTTTTTCT CTTTTTCTG TTTTTCTGC TTTTCTGCT TTTCTGCTT TTCTGCTTC TCTGCTTCC CTGCTTCCA TGCTTCCAC GCTTCCACA CTTCCACAA TTCCACAAG TCCACAAGT CCACAAGTG CACAAGTGC ACAAGTGCT CAAGTGCTT AAGTGCTTT AGTGCTTTT GTGCTTTTG TGCTTTTGT GCTTTTGTG CTTTTGTGG TTTTGTGGA TTTGTGGAA TTGTGGAAA TGTGGAAAC GTGGAAACT TGGAAACTG GGAAACTGT GAAACTGTG AAACTGTGA AACTGTGAA ACTGTGAAA CTGTGAAAG TGTGAAAGG GTGAAAGGT TGAAAGGTT GAAAGGTTT AAAGGTTTG AAGGTTTGG AGGTTTGGA GGTTTGGAT GTTTGGATT TTTGGATTA TTGGATTAT TGGATTATA GGATTATAA GATTATAAA ATTATAAAG TTATAAAGC TATAAAGCA ATAAAGCAT TAAAGCATT AAAGCATTC AAGCATTCA AGCATTCAA GCATTCAAA CATTCAAAC ATTCAAACA TTCAAACAA TCAAACAAA CAAACAAAT AAACAAATT AACAAATTG ACAAATTGT CAAATTGTT AAATTGTTG AATTGTTGA ATTGTTGAA TTGTTGAAT TGTTGAATC GTTGAATCC TTGAATCCT TGAATCCTG GAATCCTGT AATCCTGTG ATCCTGTGG TCCTGTGGT CCTGTGGTA CTGTGGTAA TGTGGTAAT GTGGTAATT TGGTAATTT GGTAATTTT GTAATTTTA TAATTTTAA AATTTTAAA ATTTTAAAG TTTTAAAGT TTTAAAGTT TTAAAGTTA TAAAGTTAC AAAGTTACA AAGTTACAA AGTTACAAA GTTACAAAA TTACAAAAG TACAAAAGG ACAAAAGGA CAAAAGGAA AAAAGGAAA AAAGGAAAA AAGGAAAAG AGGAAAAGC GGAAAAGCT GAAAAGCTA AAAAGCTAA AAAGCTAAA AAGCTAAAA AGCTAAAAA GCTAAAAAA CTAAAAAAG TAAAAAAGG AAAAAAGGT AAAAAGGTG AAAAGGTGC AAAGGTGCC AAGGTGCCT AGGTGCCTG GGTGCCTGG GTGCCTGGA TGCCTGGAA GCCTGGAAT CCTGGAATA CTGGAATAT TGGAATATT GGAATATTG GAATATTGG AATATTGGT ATATTGGTG TATTGGTGA ATTGGTGAA TTGGTGAAC TGGTGAACA GGTGAACAG GTGAACAGA TGAACAGAA GAACAGAAA AACAGAAAT ACAGAAATC CAGAAATCA AGAAATCAA GAAATCAAT AAATCAATA AATCAATAC ATCAATACT TCAATACTG CAATACTGA AATACTGAG ATACTGAGT TACTGAGTC ACTGAGTCC CTGAGTCCT TGAGTCCTC GAGTCCTCT AGTCCTCTT GTCCTCTTT TCCTCTTTA CCTCTTTAT CTCTTTATG TCTTTATGC CTTTATGCA TTTATGCAT TTATGCATT TATGCATTT ATGCATTTG TGCATTTGC GCATTTGCA CATTTGCAT ATTTGCATC TTTGCATCA TTGCATCAG TGCATCAGA GCATCAGAG CATCAGAGG ATCAGAGGC TCAGAGGCT CAGAGGCTG AGAGGCTGC GAGGCTGCT AGGCTGCTC GGCTGCTCG GCTGCTCGT CTGCTCGTG TGCTCGTGT GCTCGTGTT CTCGTGTTG TCGTGTTGT CGTGTTGTA GTGTTGTAC TGTTGTACG GTTGTACGA TTGTACGAT TGTACGATC GTACGATCA TACGATCAA ACGATCAAT CGATCAATT GATCAATTT ATCAATTTT TCAATTTTC CAATTTTCT AATTTTCTC ATTTTCTCC TTTTCTCCC TTTCTCCCG TTCTCCCGC TCTCCCGCA CTCCCGCAC TCCCGCACT CCCGCACTC CCGCACTCT CGCACTCTT GCACTCTTG CACTCTTGA ACTCTTGAA CTCTTGAAA TCTTGAAAC CTTGAAACT TTGAAACTG TGAAACTGC GAAACTGCT AAACTGCTC AACTGCTCA ACTGCTCAA CTGCTCAAA TGCTCAAAA GCTCAAAAT CTCAAAATT TCAAAATTC CAAAATTCT AAAATTCTG AAATTCTGT AATTCTGTG ATTCTGTGC TTCTGTGCG TCTGTGCGT CTGTGCGTG TGTGCGTGT GTGCGTGTT TGCGTGTTT GCGTGTTTT CGTGTTTTA GTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGA TTTACAGAA TTACAGAAG TACAGAAGG ACAGAAGGC CAGAAGGCC AGAAGGCCG GAAGGCCGC AAGGCCGCT AGGCCGCTA GGCCGCTAT GCCGCTATA CCGCTATAA CGCTATAAC GCTATAACA CTATAACAA TATAACAAT ATAACAATA TAACAATAC AACAATACT ACAATACTA CAATACTAG AATACTAGA ATACTAGAT TACTAGATG ACTAGATGG CTAGATGGA TAGATGGAA AGATGGAAT GATGGAATT ATGGAATTT TGGAATTTC GGAATTTCA GAATTTCAC AATTTCACA ATTTCACAG TTTCACAGT TTCACAGTA TCACAGTAT CACAGTATT ACAGTATTC CAGTATTCA AGTATTCAC GTATTCACT TATTCACTG ATTCACTGA TTCACTGAG TCACTGAGA CACTGAGAC ACTGAGACT CTGAGACTC TGAGACTCA GAGACTCAT AGACTCATT 

In [ ]:
PATH_files = "/content/drive/MyDrive/semantic_browser/COVID/"
k_mer_list = []
for x in tqdm(file_list):
  k_mer_aux = []
  filename = folder_path + "/" + x
  with open(filename, "r") as fp:   # Unpickling
    k_mer_aux = json.load(fp)
  k_mer_list.extend(k_mer_aux)
with open(PATH_files + "complete_kmer_list.txt", "w") as fp:   #Serialize
  json.dump(k_mer_list, fp)

 44%|████▍     | 40/90 [04:04<04:50,  5.81s/it]

In [ ]:
PATH = '/content/drive/MyDrive/semantic_browser/COVID/try2_kmer_list.txt'
with open(PATH, "r") as fp:   # Unpickling
    kmer_list_try2 = json.load(fp)

In [ ]:
print(len(kmer_list_try2))
print(kmer_list_try2[0])

3000

In [ ]:
def stack_images(iterable, n_pixels):
    """stack the images in the iterable on a (n_pixel x n_pixel) canvas"""
    
    canvas = np.zeros((n_pixels,n_pixels))
    
    for item in iterable:
        canvas += item
        
    return canvas

def get_random_image(n_pixels):
    """create a random 2D image with n_pixels on the side"""
    
    return np.random.rand(n_pixels, n_pixels)

def stack_using_generator(n_images, n_pixels):
    """iterate through a generator and stack the objects"""
    
    # notice the parentheses instead of square brackets in the next line 
    iterable = (get_random_image(n_pixels) for _ in range(n_images))
    stack_images(iterable, n_pixels)
    
    # not returning anything because I only care about the memory consumption in creating the iterable

In [ ]:
print(len(k_mer_list))
print(len(k_mer_aux))

3000
1000

In [ ]:
k_mer_list[]

'AGATCTGTT GATCTGTTC ATCTGTTCT TCTGTTCTC CTGTTCTCT TGTTCTCTA GTTCTCTAA TTCTCTAAA TCTCTAAAC CTCTAAACG TCTAAACGA CTAAACGAA TAAACGAAC AAACGAACT AACGAACTT ACGAACTTT CGAACTTTA GAACTTTAA AACTTTAAA ACTTTAAAA CTTTAAAAT TTTAAAATC TTAAAATCT TAAAATCTG AAAATCTGT AAATCTGTG AATCTGTGT ATCTGTGTG TCTGTGTGG CTGTGTGGC TGTGTGGCT GTGTGGCTG TGTGGCTGT GTGGCTGTC TGGCTGTCA GGCTGTCAC GCTGTCACT CTGTCACTC TGTCACTCG GTCACTCGG TCACTCGGC CACTCGGCT ACTCGGCTG CTCGGCTGC TCGGCTGCA CGGCTGCAT GGCTGCATG GCTGCATGC CTGCATGCT TGCATGCTT GCATGCTTA CATGCTTAG ATGCTTAGT TGCTTAGTG GCTTAGTGC CTTAGTGCA TTAGTGCAC TAGTGCACT AGTGCACTC GTGCACTCA TGCACTCAC GCACTCACG CACTCACGC ACTCACGCA CTCACGCAG TCACGCAGT CACGCAGTA ACGCAGTAT CGCAGTATA GCAGTATAA CAGTATAAT AGTATAATT GTATAATTA TATAATTAA ATAATTAAT TAATTAATA AATTAATAA ATTAATAAC TTAATAACT TAATAACTA AATAACTAA ATAACTAAT TAACTAATT AACTAATTA ACTAATTAC CTAATTACT TAATTACTG AATTACTGT ATTACTGTC TTACTGTCG TACTGTCGT ACTGTCGTT CTGTCGTTG TGTCGTTGA GTCGTTGAC TCGTTGACA CGTTGACAG GTTGACAGG TTGACAGGA TGACAGGAC GACAGGACA ACAGGACAC CAGGACACG AGGACACGA GGACACGAG GACACGAGT ACACGAGTA CACGAGTAA ACGAGTAAC CGAGTAACT GAGTAACTC AGTAACTCG GTAACTCGT TAACTCGTC AACTCGTCT ACTCGTCTA CTCGTCTAT TCGTCTATC CGTCTATCT GTCTATCTT TCTATCTTC CTATCTTCT TATCTTCTG ATCTTCTGC TCTTCTGCA CTTCTGCAG TTCTGCAGG TCTGCAGGC CTGCAGGCT TGCAGGCTG GCAGGCTGC CAGGCTGCT AGGCTGCTT GGCTGCTTA GCTGCTTAC CTGCTTACG TGCTTACGG GCTTACGGT CTTACGGTT TTACGGTTT TACGGTTTC ACGGTTTCG CGGTTTCGT GGTTTCGTC GTTTCGTCC TTTCGTCCG TTCGTCCGT TCGTCCGTG CGTCCGTGT GTCCGTGTT TCCGTGTTG CCGTGTTGC CGTGTTGCA GTGTTGCAG TGTTGCAGC GTTGCAGCC TTGCAGCCG TGCAGCCGA GCAGCCGAT CAGCCGATC AGCCGATCA GCCGATCAT CCGATCATC CGATCATCA GATCATCAG ATCATCAGC TCATCAGCA CATCAGCAC ATCAGCACA TCAGCACAT CAGCACATC AGCACATCT GCACATCTA CACATCTAG ACATCTAGG CATCTAGGT ATCTAGGTT TCTAGGTTT CTAGGTTTT TAGGTTTTG AGGTTTTGT GGTTTTGTC GTTTTGTCC TTTTGTCCG TTTGTCCGG TTGTCCGGG TGTCCGGGT GTCCGGGTG TCCGGGTGT CCGGGTGTG CGGGTGTGA GGGTGTGAC GGTGTGACC GTGTGACCG TGTGACCGA GTGACCGAA TGACCGAAA GACCGAAAG ACCGAAAGG CCGAAAGGT CGAAAGGTA GAAAGGTAA AAAGGTAAG AAGGTAAGA AGGTAAGAT GGTAAGATG GTAAGATGG TAAGATGGA AAGATGGAG AGATGGAGA GATGGAGAG ATGGAGAGC TGGAGAGCC GGAGAGCCT GAGAGCCTT AGAGCCTTG GAGCCTTGT AGCCTTGTC GCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTG TGTCCCTGG GTCCCTGGT TCCCTGGTT CCCTGGTTT CCTGGTTTC CTGGTTTCA TGGTTTCAA GGTTTCAAC GTTTCAACG TTTCAACGA TTCAACGAG TCAACGAGA CAACGAGAA AACGAGAAA ACGAGAAAA CGAGAAAAC GAGAAAACA AGAAAACAC GAAAACACA AAAACACAC AAACACACG AACACACGT ACACACGTC CACACGTCC ACACGTCCA CACGTCCAA ACGTCCAAC CGTCCAACT GTCCAACTC TCCAACTCA CCAACTCAG CAACTCAGT AACTCAGTT ACTCAGTTT CTCAGTTTG TCAGTTTGC CAGTTTGCC AGTTTGCCT GTTTGCCTG TTTGCCTGT TTGCCTGTT TGCCTGTTT GCCTGTTTT CCTGTTTTA CTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGG TTTACAGGT TTACAGGTT TACAGGTTC ACAGGTTCG CAGGTTCGC AGGTTCGCG GGTTCGCGA GTTCGCGAC TTCGCGACG TCGCGACGT CGCGACGTG GCGACGTGC CGACGTGCT GACGTGCTC ACGTGCTCG CGTGCTCGT GTGCTCGTA TGCTCGTAC GCTCGTACG CTCGTACGT TCGTACGTG CGTACGTGG GTACGTGGC TACGTGGCT ACGTGGCTT CGTGGCTTT GTGGCTTTG TGGCTTTGG GGCTTTGGA GCTTTGGAG CTTTGGAGA TTTGGAGAC TTGGAGACT TGGAGACTC GGAGACTCC GAGACTCCG AGACTCCGT GACTCCGTG ACTCCGTGG CTCCGTGGA TCCGTGGAG CCGTGGAGG CGTGGAGGA GTGGAGGAG TGGAGGAGG GGAGGAGGT GAGGAGGTC AGGAGGTCT GGAGGTCTT GAGGTCTTA AGGTCTTAT GGTCTTATC GTCTTATCA TCTTATCAG CTTATCAGA TTATCAGAG TATCAGAGG ATCAGAGGC TCAGAGGCA CAGAGGCAC AGAGGCACG GAGGCACGT AGGCACGTC GGCACGTCA GCACGTCAA CACGTCAAC ACGTCAACA CGTCAACAT GTCAACATC TCAACATCT CAACATCTT AACATCTTA ACATCTTAA CATCTTAAA ATCTTAAAG TCTTAAAGA CTTAAAGAT TTAAAGATG TAAAGATGG AAAGATGGC AAGATGGCA AGATGGCAC GATGGCACT ATGGCACTT TGGCACTTG GGCACTTGT GCACTTGTG CACTTGTGG ACTTGTGGC CTTGTGGCT TTGTGGCTT TGTGGCTTA GTGGCTTAG TGGCTTAGT GGCTTAGTA GCTTAGTAG CTTAGTAGA TTAGTAGAA TAGTAGAAG AGTAGAAGT GTAGAAGTT TAGAAGTTG AGAAGTTGA GAAGTTGAA AAGTTGAAA AGTTGAAAA GTTGAAAAA TTGAAAAAG TGAAAAAGG GAAAAAGGC AAAAAGGCG AAAAGGCGT AAAGGCGTT AAGGCGTTT AGGCGTTTT GGCGTTTTG GCGTTTTGC CGTTTTGCC GTTTTGCCT TTTTGCCTC TTTGCCTCA TTGCCTCAA TGCCTCAAC GCCTCAACT CCTCAACTT CTCAACTTG TCAACTTGA CAACTTGAA AACTTGAAC ACTTGAACA CTTGAACAG TTGAACAGC TGAACAGCC GAACAGCCC AACAGCCCT ACAGCCCTA CAGCCCTAT AGCCCTATG GCCCTATGT CCCTATGTG CCTATGTGT CTATGTGTT TATGTGTTC ATGTGTTCA TGTGTTCAT GTGTTCATC TGTTCATCA GTTCATCAA TTCATCAAA TCATCAAAC CATCAAACG ATCAAACGT TCAAACGTT CAAACGTTC AAACGTTCG AACGTTCGG ACGTTCGGA CGTTCGGAT GTTCGGATG TTCGGATGC TCGGATGCT CGGATGCTC GGATGCTCG GATGCTCGA ATGCTCGAA TGCTCGAAC GCTCGAACT CTCGAACTG TCGAACTGC CGAACTGCA GAACTGCAC AACTGCACC ACTGCACCT CTGCACCTC TGCACCTCA GCACCTCAT CACCTCATG ACCTCATGG CCTCATGGT CTCATGGTC TCATGGTCA CATGGTCAT ATGGTCATG TGGTCATGT GGTCATGTT GTCATGTTA TCATGTTAT CATGTTATG ATGTTATGG TGTTATGGT GTTATGGTT TTATGGTTG TATGGTTGA ATGGTTGAG TGGTTGAGC GGTTGAGCT GTTGAGCTG TTGAGCTGG TGAGCTGGT GAGCTGGTA AGCTGGTAG GCTGGTAGC CTGGTAGCA TGGTAGCAG GGTAGCAGA GTAGCAGAA TAGCAGAAC AGCAGAACT GCAGAACTC CAGAACTCG AGAACTCGA GAACTCGAA AACTCGAAG ACTCGAAGG CTCGAAGGC TCGAAGGCA CGAAGGCAT GAAGGCATT AAGGCATTC AGGCATTCA GGCATTCAG GCATTCAGT CATTCAGTA ATTCAGTAC TTCAGTACG TCAGTACGG CAGTACGGT AGTACGGTC GTACGGTCG TACGGTCGT ACGGTCGTA CGGTCGTAG GGTCGTAGT GTCGTAGTG TCGTAGTGG CGTAGTGGT GTAGTGGTG TAGTGGTGA AGTGGTGAG GTGGTGAGA TGGTGAGAC GGTGAGACA GTGAGACAC TGAGACACT GAGACACTT AGACACTTG GACACTTGG ACACTTGGT CACTTGGTG ACTTGGTGT CTTGGTGTC TTGGTGTCC TGGTGTCCT GGTGTCCTT GTGTCCTTG TGTCCTTGT GTCCTTGTC TCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTC TGTCCCTCA GTCCCTCAT TCCCTCATG CCCTCATGT CCTCATGTG CTCATGTGG TCATGTGGG CATGTGGGC ATGTGGGCG TGTGGGCGA GTGGGCGAA TGGGCGAAA GGGCGAAAT GGCGAAATA GCGAAATAC CGAAATACC GAAATACCA AAATACCAG AATACCAGT ATACCAGTG TACCAGTGG ACCAGTGGC CCAGTGGCT CAGTGGCTT AGTGGCTTA GTGGCTTAC TGGCTTACC GGCTTACCG GCTTACCGC CTTACCGCA TTACCGCAA TACCGCAAG ACCGCAAGG CCGCAAGGT CGCAAGGTT GCAAGGTTC CAAGGTTCT AAGGTTCTT AGGTTCTTC GGTTCTTCT GTTCTTCTT TTCTTCTTC TCTTCTTCG CTTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGA TCGTAAGAA CGTAAGAAC GTAAGAACG TAAGAACGG AAGAACGGT AGAACGGTA GAACGGTAA AACGGTAAT ACGGTAATA CGGTAATAA GGTAATAAA GTAATAAAG TAATAAAGG AATAAAGGA ATAAAGGAG TAAAGGAGC AAAGGAGCT AAGGAGCTG AGGAGCTGG GGAGCTGGT GAGCTGGTG AGCTGGTGG GCTGGTGGC CTGGTGGCC TGGTGGCCA GGTGGCCAT GTGGCCATA TGGCCATAG GGCCATAGT GCCATAGTT CCATAGTTA CATAGTTAC ATAGTTACG TAGTTACGG AGTTACGGC GTTACGGCG TTACGGCGC TACGGCGCC ACGGCGCCG CGGCGCCGA GGCGCCGAT GCGCCGATC CGCCGATCT GCCGATCTA CCGATCTAA CGATCTAAA GATCTAAAG ATCTAAAGT TCTAAAGTC CTAAAGTCA TAAAGTCAT AAAGTCATT AAGTCATTT AGTCATTTG GTCATTTGA TCATTTGAC CATTTGACT ATTTGACTT TTTGACTTA TTGACTTAG TGACTTAGG GACTTAGGC ACTTAGGCG CTTAGGCGA TTAGGCGAC TAGGCGACG AGGCGACGA GGCGACGAG GCGACGAGC CGACGAGCT GACGAGCTT ACGAGCTTG CGAGCTTGG GAGCTTGGC AGCTTGGCA GCTTGGCAC CTTGGCACT TTGGCACTG TGGCACTGA GGCACTGAT GCACTGATC CACTGATCC ACTGATCCT CTGATCCTT TGATCCTTA GATCCTTAT ATCCTTATG TCCTTATGA CCTTATGAA CTTATGAAG TTATGAAGA TATGAAGAT ATGAAGATT TGAAGATTT GAAGATTTT AAGATTTTC AGATTTTCA GATTTTCAA ATTTTCAAG TTTTCAAGA TTTCAAGAA TTCAAGAAA TCAAGAAAA CAAGAAAAC AAGAAAACT AGAAAACTG GAAAACTGG AAAACTGGA AAACTGGAA AACTGGAAC ACTGGAACA CTGGAACAC TGGAACACT GGAACACTA GAACACTAA AACACTAAA ACACTAAAC CACTAAACA ACTAAACAT CTAAACATA TAAACATAG AAACATAGC AACATAGCA ACATAGCAG CATAGCAGT ATAGCAGTG TAGCAGTGG AGCAGTGGT GCAGTGGTG CAGTGGTGT AGTGGTGTT GTGGTGTTA TGGTGTTAC GGTGTTACC GTGTTACCC TGTTACCCG GTTACCCGT TTACCCGTG TACCCGTGA ACCCGTGAA CCCGTGAAC CCGTGAACT CGTGAACTC GTGAACTCA TGAACTCAT GAACTCATG AACTCATGC ACTCATGCG CTCATGCGT TCATGCGTG CATGCGTGA ATGCGTGAG TGCGTGAGC GCGTGAGCT CGTGAGCTT GTGAGCTTA TGAGCTTAA GAGCTTAAC AGCTTAACG GCTTAACGG CTTAACGGA TTAACGGAG TAACGGAGG AACGGAGGG ACGGAGGGG CGGAGGGGC GGAGGGGCA GAGGGGCAT AGGGGCATA GGGGCATAC GGGCATACA GGCATACAC GCATACACT CATACACTC ATACACTCG TACACTCGC ACACTCGCT CACTCGCTA ACTCGCTAT CTCGCTATG TCGCTATGT CGCTATGTC GCTATGTCG CTATGTCGA TATGTCGAT ATGTCGATA TGTCGATAA GTCGATAAC TCGATAACA CGATAACAA GATAACAAC ATAACAACT TAACAACTT AACAACTTC ACAACTTCT CAACTTCTG AACTTCTGT ACTTCTGTG CTTCTGTGG TTCTGTGGC TCTGTGGCC CTGTGGCCC TGTGGCCCT GTGGCCCTG TGGCCCTGA GGCCCTGAT GCCCTGATG CCCTGATGG CCTGATGGC CTGATGGCT TGATGGCTA GATGGCTAC ATGGCTACC TGGCTACCC GGCTACCCT GCTACCCTC CTACCCTCT TACCCTCTT ACCCTCTTG CCCTCTTGA CCTCTTGAG CTCTTGAGT TCTTGAGTG CTTGAGTGC TTGAGTGCA TGAGTGCAT GAGTGCATT AGTGCATTA GTGCATTAA TGCATTAAA GCATTAAAG CATTAAAGA ATTAAAGAC TTAAAGACC TAAAGACCT AAAGACCTT AAGACCTTC AGACCTTCT GACCTTCTA ACCTTCTAG CCTTCTAGC CTTCTAGCA TTCTAGCAC TCTAGCACG CTAGCACGT TAGCACGTG AGCACGTGC GCACGTGCT CACGTGCTG ACGTGCTGG CGTGCTGGT GTGCTGGTA TGCTGGTAA GCTGGTAAA CTGGTAAAG TGGTAAAGC GGTAAAGCT GTAAAGCTT TAAAGCTTC AAAGCTTCA AAGCTTCAT AGCTTCATG GCTTCATGC CTTCATGCA TTCATGCAC TCATGCACT CATGCACTT ATGCACTTT TGCACTTTG GCACTTTGT CACTTTGTC ACTTTGTCC CTTTGTCCG TTTGTCCGA TTGTCCGAA TGTCCGAAC GTCCGAACA TCCGAACAA CCGAACAAC CGAACAACT GAACAACTG AACAACTGG ACAACTGGA CAACTGGAC AACTGGACT ACTGGACTT CTGGACTTT TGGACTTTA GGACTTTAT GACTTTATT ACTTTATTG CTTTATTGA TTTATTGAC TTATTGACA TATTGACAC ATTGACACT TTGACACTA TGACACTAA GACACTAAG ACACTAAGA CACTAAGAG ACTAAGAGG CTAAGAGGG TAAGAGGGG AAGAGGGGT AGAGGGGTG GAGGGGTGT AGGGGTGTA GGGGTGTAT GGGTGTATA GGTGTATAC GTGTATACT TGTATACTG GTATACTGC TATACTGCT ATACTGCTG TACTGCTGC ACTGCTGCC CTGCTGCCG TGCTGCCGT GCTGCCGTG CTGCCGTGA TGCCGTGAA GCCGTGAAC CCGTGAACA CGTGAACAT GTGAACATG TGAACATGA GAACATGAG AACATGAGC ACATGAGCA CATGAGCAT ATGAGCATG TGAGCATGA GAGCATGAA AGCATGAAA GCATGAAAT CATGAAATT ATGAAATTG TGAAATTGC GAAATTGCT AAATTGCTT AATTGCTTG ATTGCTTGG TTGCTTGGT TGCTTGGTA GCTTGGTAC CTTGGTACA TTGGTACAC TGGTACACG GGTACACGG GTACACGGA TACACGGAA ACACGGAAC CACGGAACG ACGGAACGT CGGAACGTT GGAACGTTC GAACGTTCT AACGTTCTG ACGTTCTGA CGTTCTGAA GTTCTGAAA TTCTGAAAA TCTGAAAAG CTGAAAAGA TGAAAAGAG GAAAAGAGC AAAAGAGCT AAAGAGCTA AAGAGCTAT AGAGCTATG GAGCTATGA AGCTATGAA GCTATGAAT CTATGAATT TATGAATTG ATGAATTGC TGAATTGCA GAATTGCAG AATTGCAGA ATTGCAGAC TTGCAGACA TGCAGACAC GCAGACACC CAGACACCT AGACACCTT GACACCTTT ACACCTTTT CACCTTTTG ACCTTTTGA CCTTTTGAA CTTTTGAAA TTTTGAAAT TTTGAAATT TTGAAATTA TGAAATTAA GAAATTAAA AAATTAAAT AATTAAATT ATTAAATTG TTAAATTGG TAAATTGGC AAATTGGCA AATTGGCAA ATTGGCAAA TTGGCAAAG TGGCAAAGA GGCAAAGAA GCAAAGAAA CAAAGAAAT AAAGAAATT AAGAAATTT AGAAATTTG GAAATTTGA AAATTTGAC AATTTGACA ATTTGACAC TTTGACACC TTGACACCT TGACACCTT GACACCTTC ACACCTTCA CACCTTCAA ACCTTCAAT CCTTCAATG CTTCAATGG TTCAATGGG TCAATGGGG CAATGGGGA AATGGGGAA ATGGGGAAT TGGGGAATG GGGGAATGT GGGAATGTC GGAATGTCC GAATGTCCA AATGTCCAA ATGTCCAAA TGTCCAAAT GTCCAAATT TCCAAATTT CCAAATTTT CAAATTTTG AAATTTTGT AATTTTGTA ATTTTGTAT TTTTGTATT TTTGTATTT TTGTATTTC TGTATTTCC GTATTTCCC TATTTCCCT ATTTCCCTT TTTCCCTTA TTCCCTTAA TCCCTTAAA CCCTTAAAT CCTTAAATT CTTAAATTC TTAAATTCC TAAATTCCA AAATTCCAT AATTCCATA ATTCCATAA TTCCATAAT TCCATAATC CCATAATCA CATAATCAA ATAATCAAG TAATCAAGA AATCAAGAC ATCAAGACT TCAAGACTA CAAGACTAT AAGACTATT AGACTATTC GACTATTCA ACTATTCAA CTATTCAAC TATTCAACC ATTCAACCA TTCAACCAA TCAACCAAG CAACCAAGG AACCAAGGG ACCAAGGGT CCAAGGGTT CAAGGGTTG AAGGGTTGA AGGGTTGAA GGGTTGAAA GGTTGAAAA GTTGAAAAG TTGAAAAGA TGAAAAGAA GAAAAGAAA AAAAGAAAA AAAGAAAAA AAGAAAAAG AGAAAAAGC GAAAAAGCT AAAAAGCTT AAAAGCTTG AAAGCTTGA AAGCTTGAT AGCTTGATG GCTTGATGG CTTGATGGC TTGATGGCT TGATGGCTT GATGGCTTT ATGGCTTTA TGGCTTTAT GGCTTTATG GCTTTATGG CTTTATGGG TTTATGGGT TTATGGGTA TATGGGTAG ATGGGTAGA TGGGTAGAA GGGTAGAAT GGTAGAATT GTAGAATTC TAGAATTCG AGAATTCGA GAATTCGAT AATTCGATC ATTCGATCT TTCGATCTG TCGATCTGT CGATCTGTC GATCTGTCT ATCTGTCTA TCTGTCTAT CTGTCTATC TGTCTATCC GTCTATCCA TCTATCCAG CTATCCAGT TATCCAGTT ATCCAGTTG TCCAGTTGC CCAGTTGCG CAGTTGCGT AGTTGCGTC GTTGCGTCA TTGCGTCAC TGCGTCACC GCGTCACCA CGTCACCAA GTCACCAAA TCACCAAAT CACCAAATG ACCAAATGA CCAAATGAA CAAATGAAT AAATGAATG AATGAATGC ATGAATGCA TGAATGCAA GAATGCAAC AATGCAACC ATGCAACCA TGCAACCAA GCAACCAAA CAACCAAAT AACCAAATG ACCAAATGT CCAAATGTG CAAATGTGC AAATGTGCC AATGTGCCT ATGTGCCTT TGTGCCTTT GTGCCTTTT TGCCTTTTA GCCTTTTAA CCTTTTAAC CTTTTAACT TTTTAACTC TTTAACTCT TTAACTCTC TAACTCTCA AACTCTCAT ACTCTCATG CTCTCATGA TCTCATGAA CTCATGAAG TCATGAAGT CATGAAGTG ATGAAGTGT TGAAGTGTG GAAGTGTGA AAGTGTGAT AGTGTGATC GTGTGATCA TGTGATCAT GTGATCATT TGATCATTG GATCATTGT ATCATTGTG TCATTGTGG CATTGTGGT ATTGTGGTG TTGTGGTGA TGTGGTGAA GTGGTGAAA TGGTGAAAC GGTGAAACT GTGAAACTT TGAAACTTC GAAACTTCA AAACTTCAT AACTTCATG ACTTCATGG CTTCATGGC TTCATGGCA TCATGGCAG CATGGCAGA ATGGCAGAC TGGCAGACG GGCAGACGG GCAGACGGG CAGACGGGC AGACGGGCG GACGGGCGA ACGGGCGAT CGGGCGATT GGGCGATTT GGCGATTTT GCGATTTTG CGATTTTGT GATTTTGTT ATTTTGTTA TTTTGTTAA TTTGTTAAA TTGTTAAAG TGTTAAAGC GTTAAAGCC TTAAAGCCA TAAAGCCAC AAAGCCACT AAGCCACTT AGCCACTTG GCCACTTGT CCACTTGTG CACTTGTGA ACTTGTGAA CTTGTGAAT TTGTGAATT TGTGAATTT GTGAATTTT TGAATTTTG GAATTTTGT AATTTTGTG ATTTTGTGG TTTTGTGGC TTTGTGGCA TTGTGGCAC TGTGGCACT GTGGCACTG TGGCACTGA GGCACTGAG GCACTGAGA CACTGAGAA ACTGAGAAT CTGAGAATT TGAGAATTT GAGAATTTG AGAATTTGA GAATTTGAC AATTTGACT ATTTGACTA TTTGACTAA TTGACTAAA TGACTAAAG GACTAAAGA ACTAAAGAA CTAAAGAAG TAAAGAAGG AAAGAAGGT AAGAAGGTG AGAAGGTGC GAAGGTGCC AAGGTGCCA AGGTGCCAC GGTGCCACT GTGCCACTA TGCCACTAC GCCACTACT CCACTACTT CACTACTTG ACTACTTGT CTACTTGTG TACTTGTGG ACTTGTGGT CTTGTGGTT TTGTGGTTA TGTGGTTAC GTGGTTACT TGGTTACTT GGTTACTTA GTTACTTAC TTACTTACC TACTTACCC ACTTACCCC CTTACCCCA TTACCCCAA TACCCCAAA ACCCCAAAA CCCCAAAAT CCCAAAATG CCAAAATGC CAAAATGCT AAAATGCTG AAATGCTGT AATGCTGTT ATGCTGTTG TGCTGTTGT GCTGTTGTT CTGTTGTTA TGTTGTTAA GTTGTTAAA TTGTTAAAA TGTTAAAAT GTTAAAATT TTAAAATTT TAAAATTTA AAAATTTAT AAATTTATT AATTTATTG ATTTATTGT TTTATTGTC TTATTGTCC TATTGTCCA ATTGTCCAG TTGTCCAGC TGTCCAGCA GTCCAGCAT TCCAGCATG CCAGCATGT CAGCATGTC AGCATGTCA GCATGTCAC CATGTCACA ATGTCACAA TGTCACAAT GTCACAATT TCACAATTC CACAATTCA ACAATTCAG CAATTCAGA AATTCAGAA ATTCAGAAG TTCAGAAGT TCAGAAGTA CAGAAGTAG AGAAGTAGG GAAGTAGGA AAGTAGGAC AGTAGGACC GTAGGACCT TAGGACCTG AGGACCTGA GGACCTGAG GACCTGAGC ACCTGAGCA CCTGAGCAT CTGAGCATA TGAGCATAG GAGCATAGT AGCATAGTC GCATAGTCT CATAGTCTT ATAGTCTTG TAGTCTTGC AGTCTTGCC GTCTTGCCG TCTTGCCGA CTTGCCGAA TTGCCGAAT TGCCGAATA GCCGAATAC CCGAATACC CGAATACCA GAATACCAT AATACCATA ATACCATAA TACCATAAT ACCATAATG CCATAATGA CATAATGAA ATAATGAAT TAATGAATC AATGAATCT ATGAATCTG TGAATCTGG GAATCTGGC AATCTGGCT ATCTGGCTT TCTGGCTTG CTGGCTTGA TGGCTTGAA GGCTTGAAA GCTTGAAAA CTTGAAAAC TTGAAAACC TGAAAACCA GAAAACCAT AAAACCATT AAACCATTC AACCATTCT ACCATTCTT CCATTCTTC CATTCTTCG ATTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGG TCGTAAGGG CGTAAGGGT GTAAGGGTG TAAGGGTGG AAGGGTGGT AGGGTGGTC GGGTGGTCG GGTGGTCGC GTGGTCGCA TGGTCGCAC GGTCGCACT GTCGCACTA TCGCACTAT CGCACTATT GCACTATTG CACTATTGC ACTATTGCC CTATTGCCT TATTGCCTT ATTGCCTTT TTGCCTTTG TGCCTTTGG GCCTTTGGA CCTTTGGAG CTTTGGAGG TTTGGAGGC TTGGAGGCT TGGAGGCTG GGAGGCTGT GAGGCTGTG AGGCTGTGT GGCTGTGTG GCTGTGTGT CTGTGTGTT TGTGTGTTC GTGTGTTCT TGTGTTCTC GTGTTCTCT TGTTCTCTT GTTCTCTTA TTCTCTTAT TCTCTTATG CTCTTATGT TCTTATGTT CTTATGTTG TTATGTTGG TATGTTGGT ATGTTGGTT TGTTGGTTG GTTGGTTGC TTGGTTGCC TGGTTGCCA GGTTGCCAT GTTGCCATA TTGCCATAA TGCCATAAC GCCATAACA CCATAACAA CATAACAAG ATAACAAGT TAACAAGTG AACAAGTGT ACAAGTGTG CAAGTGTGC AAGTGTGCC AGTGTGCCT GTGTGCCTA TGTGCCTAT GTGCCTATT TGCCTATTG GCCTATTGG CCTATTGGG CTATTGGGT TATTGGGTT ATTGGGTTC TTGGGTTCC TGGGTTCCA GGGTTCCAC GGTTCCACG GTTCCACGT TTCCACGTG TCCACGTGC CCACGTGCT CACGTGCTA ACGTGCTAG CGTGCTAGC GTGCTAGCG TGCTAGCGC GCTAGCGCT CTAGCGCTA TAGCGCTAA AGCGCTAAC GCGCTAACA CGCTAACAT GCTAACATA CTAACATAG TAACATAGG AACATAGGT ACATAGGTT CATAGGTTG ATAGGTTGT TAGGTTGTA AGGTTGTAA GGTTGTAAC GTTGTAACC TTGTAACCA TGTAACCAT GTAACCATA TAACCATAC AACCATACA ACCATACAG CCATACAGG CATACAGGT ATACAGGTG TACAGGTGT ACAGGTGTT CAGGTGTTG AGGTGTTGT GGTGTTGTT GTGTTGTTG TGTTGTTGG GTTGTTGGA TTGTTGGAG TGTTGGAGA GTTGGAGAA TTGGAGAAG TGGAGAAGG GGAGAAGGT GAGAAGGTT AGAAGGTTC GAAGGTTCC AAGGTTCCG AGGTTCCGA GGTTCCGAA GTTCCGAAG TTCCGAAGG TCCGAAGGT CCGAAGGTC CGAAGGTCT GAAGGTCTT AAGGTCTTA AGGTCTTAA GGTCTTAAT GTCTTAATG TCTTAATGA CTTAATGAC TTAATGACA TAATGACAA AATGACAAC ATGACAACC TGACAACCT GACAACCTT ACAACCTTC CAACCTTCT AACCTTCTT ACCTTCTTG CCTTCTTGA CTTCTTGAA TTCTTGAAA TCTTGAAAT CTTGAAATA TTGAAATAC TGAAATACT GAAATACTC AAATACTCC AATACTCCA ATACTCCAA TACTCCAAA ACTCCAAAA CTCCAAAAA TCCAAAAAG CCAAAAAGA CAAAAAGAG AAAAAGAGA AAAAGAGAA AAAGAGAAA AAGAGAAAG AGAGAAAGT GAGAAAGTC AGAAAGTCA GAAAGTCAA AAAGTCAAC AAGTCAACA AGTCAACAT GTCAACATC TCAACATCA CAACATCAA AACATCAAT ACATCAATA CATCAATAT ATCAATATT TCAATATTG CAATATTGT AATATTGTT ATATTGTTG TATTGTTGG ATTGTTGGT TTGTTGGTG TGTTGGTGA GTTGGTGAC TTGGTGACT TGGTGACTT GGTGACTTT GTGACTTTA TGACTTTAA GACTTTAAA ACTTTAAAC CTTTAAACT TTTAAACTT TTAAACTTA TAAACTTAA AAACTTAAT AACTTAATG ACTTAATGA CTTAATGAA TTAATGAAG TAATGAAGA AATGAAGAG ATGAAGAGA TGAAGAGAT GAAGAGATC AAGAGATCG AGAGATCGC GAGATCGCC AGATCGCCA GATCGCCAT ATCGCCATT TCGCCATTA CGCCATTAT GCCATTATT CCATTATTT CATTATTTT ATTATTTTG TTATTTTGG TATTTTGGC ATTTTGGCA TTTTGGCAT TTTGGCATC TTGGCATCT TGGCATCTT GGCATCTTT GCATCTTTT CATCTTTTT ATCTTTTTC TCTTTTTCT CTTTTTCTG TTTTTCTGC TTTTCTGCT TTTCTGCTT TTCTGCTTC TCTGCTTCC CTGCTTCCA TGCTTCCAC GCTTCCACA CTTCCACAA TTCCACAAG TCCACAAGT CCACAAGTG CACAAGTGC ACAAGTGCT CAAGTGCTT AAGTGCTTT AGTGCTTTT GTGCTTTTG TGCTTTTGT GCTTTTGTG CTTTTGTGG TTTTGTGGA TTTGTGGAA TTGTGGAAA TGTGGAAAC GTGGAAACT TGGAAACTG GGAAACTGT GAAACTGTG AAACTGTGA AACTGTGAA ACTGTGAAA CTGTGAAAG TGTGAAAGG GTGAAAGGT TGAAAGGTT GAAAGGTTT AAAGGTTTG AAGGTTTGG AGGTTTGGA GGTTTGGAT GTTTGGATT TTTGGATTA TTGGATTAT TGGATTATA GGATTATAA GATTATAAA ATTATAAAG TTATAAAGC TATAAAGCA ATAAAGCAT TAAAGCATT AAAGCATTC AAGCATTCA AGCATTCAA GCATTCAAA CATTCAAAC ATTCAAACA TTCAAACAA TCAAACAAA CAAACAAAT AAACAAATT AACAAATTG ACAAATTGT CAAATTGTT AAATTGTTG AATTGTTGA ATTGTTGAA TTGTTGAAT TGTTGAATC GTTGAATCC TTGAATCCT TGAATCCTG GAATCCTGT AATCCTGTG ATCCTGTGG TCCTGTGGT CCTGTGGTA CTGTGGTAA TGTGGTAAT GTGGTAATT TGGTAATTT GGTAATTTT GTAATTTTA TAATTTTAA AATTTTAAA ATTTTAAAG TTTTAAAGT TTTAAAGTT TTAAAGTTA TAAAGTTAC AAAGTTACA AAGTTACAA AGTTACAAA GTTACAAAA TTACAAAAG TACAAAAGG ACAAAAGGA CAAAAGGAA AAAAGGAAA AAAGGAAAA AAGGAAAAG AGGAAAAGC GGAAAAGCT GAAAAGCTA AAAAGCTAA AAAGCTAAA AAGCTAAAA AGCTAAAAA GCTAAAAAA CTAAAAAAG TAAAAAAGG AAAAAAGGT AAAAAGGTG AAAAGGTGC AAAGGTGCC AAGGTGCCT AGGTGCCTG GGTGCCTGG GTGCCTGGA TGCCTGGAA GCCTGGAAT CCTGGAATA CTGGAATAT TGGAATATT GGAATATTG GAATATTGG AATATTGGT ATATTGGTG TATTGGTGA ATTGGTGAA TTGGTGAAC TGGTGAACA GGTGAACAG GTGAACAGA TGAACAGAA GAACAGAAA AACAGAAAT ACAGAAATC CAGAAATCA AGAAATCAA GAAATCAAT AAATCAATA AATCAATAC ATCAATACT TCAATACTG CAATACTGA AATACTGAG ATACTGAGT TACTGAGTC ACTGAGTCC CTGAGTCCT TGAGTCCTC GAGTCCTCT AGTCCTCTT GTCCTCTTT TCCTCTTTA CCTCTTTAT CTCTTTATG TCTTTATGC CTTTATGCA TTTATGCAT TTATGCATT TATGCATTT ATGCATTTG TGCATTTGC GCATTTGCA CATTTGCAT ATTTGCATC TTTGCATCA TTGCATCAG TGCATCAGA GCATCAGAG CATCAGAGG ATCAGAGGC TCAGAGGCT CAGAGGCTG AGAGGCTGC GAGGCTGCT AGGCTGCTC GGCTGCTCG GCTGCTCGT CTGCTCGTG TGCTCGTGT GCTCGTGTT CTCGTGTTG TCGTGTTGT CGTGTTGTA GTGTTGTAC TGTTGTACG GTTGTACGA TTGTACGAT TGTACGATC GTACGATCA TACGATCAA ACGATCAAT CGATCAATT GATCAATTT ATCAATTTT TCAATTTTC CAATTTTCT AATTTTCTC ATTTTCTCC TTTTCTCCC TTTCTCCCG TTCTCCCGC TCTCCCGCA CTCCCGCAC TCCCGCACT CCCGCACTC CCGCACTCT CGCACTCTT GCACTCTTG CACTCTTGA ACTCTTGAA CTCTTGAAA TCTTGAAAC CTTGAAACT TTGAAACTG TGAAACTGC GAAACTGCT AAACTGCTC AACTGCTCA ACTGCTCAA CTGCTCAAA TGCTCAAAA GCTCAAAAT CTCAAAATT TCAAAATTC CAAAATTCT AAAATTCTG AAATTCTGT AATTCTGTG ATTCTGTGC TTCTGTGCG TCTGTGCGT CTGTGCGTG TGTGCGTGT GTGCGTGTT TGCGTGTTT GCGTGTTTT CGTGTTTTA GTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGA TTTACAGAA TTACAGAAG TACAGAAGG ACAGAAGGC CAGAAGGCC AGAAGGCCG GAAGGCCGC AAGGCCGCT AGGCCGCTA GGCCGCTAT GCCGCTATA CCGCTATAA CGCTATAAC GCTATAACA CTATAACAA TATAACAAT ATAACAATA TAACAATAC AACAATACT ACAATACTA CAATACTAG AATACTAGA ATACTAGAT TACTAGATG ACTAGATGG CTAGATGGA TAGATGGAA AGATGGAAT GATGGAATT ATGGAATTT TGGAATTTC GGAATTTCA GAATTTCAC AATTTCACA ATTTCACAG TTTCACAGT TTCACAGTA TCACAGTAT CACAGTATT ACAGTATTC CAGTATTCA AGTATTCAC GTATTCACT TATTCACTG ATTCACTGA TTCACTGAG TCACTGAGA CACTGAGAC ACTGAGACT CTGAGACTC TGAGACTCA GAGACTCAT AGACTCATT GACTCATTG ACTCATTGA CTCATTGAT TCATTGATG CATTGATGC ATTGATGCT TTGATGCTA TGATGCTAT GATGCTATG ATGCTATGA TGCTATGAT GCTATGATG CTATGATGT TATGATGTT ATGATGTTC TGATGTTCA GATGTTCAC ATGTTCACA TGTTCACAT GTTCACATC TTCACATCT TCACATCTG CACATCTGA ACATCTGAT CATCTGATT ATCTGATTT TCTGATTTG CTGATTTGG TGATTTGGC GATTTGGCT ATTTGGCTA TTTGGCTAC TTGGCTACT TGGCTACTA GGCTACTAA GCTACTAAC CTACTAACA TACTAACAA ACTAACAAT CTAACAATC TAACAATCT AACAATCTA ACAATCTAG CAATCTAGT AATCTAGTT ATCTAGTTG TCTAGTTGT CTAGTTGTA TAGTTGTAA AGTTGTAAT GTTGTAATG TTGTAATGG TGTAATGGC GTAATGGCC

In [ ]:
frames = [df, df2]
df2 = pd.DataFrame(example2)
result = pd.concat(frames)

In [ ]:
result

                                                   0
0  ATTAAAGGT TTAAAGGTT TAAAGGTTT AAAGGTTTA AAGGTT...
1  ACAAACCAA CAAACCAAC AAACCAACC AACCAACCA ACCAAC...
2  ATTAAAGGT TTAAAGGTT TAAAGGTTT AAAGGTTTA AAGGTT...
3  TTCCCAGGT TCCCAGGTA CCCAGGTAA CCAGGTAAC CAGGTA...
4  GGTTTATAC GTTTATACC TTTATACCT TTATACCTT TATACC...
5  AACTTTAAA ACTTTAAAA CTTTAAAAT TTTAAAATC TTAAAA...
6  CATGCTTAG ATGCTTAGT TGCTTAGTG GCTTAGTGC CTTAGT...
7  GATCTCTTG ATCTCTTGT TCTCTTGTA CTCTTGTAG TCTTGT...
8  GATCTCTTG ATCTCTTGT TCTCTTGTA CTCTTGTAG TCTTGT...
9  GATCTCTTG ATCTCTTGT TCTCTTGTA CTCTTGTAG TCTTGT...
0  TCTCTTGTA CTCTTGTAG TCTTGTAGA CTTGTAGAT TTGTAG...
1  TCTCTTGTA CTCTTGTAG TCTTGTAGA CTTGTAGAT TTGTAG...
2  TGTAGATCT GTAGATCTG TAGATCTGT AGATCTGTT GATCTG...
3  GGTTTATAC GTTTATACC TTTATACCT TTATACCTT TATACC...
4  TTAATAGGT TAATAGGTT AATAGGTTT ATAGGTTTA TAGGTT...
5  GGTTTATAC GTTTATACC TTTATACCT TTATACCTT TATACC...
6  GGTTTATAC GTTTATACC TTTATACCT TTATACCTT TATACC...
7  TTTAAAGGT TTAAAGGTT TAAAGGTTT AAAGGTTTA AAGGTT...
8  TTAATAGGT TAATAGGTT AATAGGTTT ATAGGTTTA TAGGTT...
9  TAATAGGTT AATAGGTTT ATAGGTTTA TAGGTTTAT AGGTTT...

In [ ]:
# Reset index enumeration
result.reset_index(drop=True, inplace=True)

In [ ]:
result.columns = ['try']
result['try'][19]

'TAATAGGTT AATAGGTTT ATAGGTTTA TAGGTTTAT AGGTTTATA GGTTTATAC GTTTATACC TTTATACCT TTATACCTT TATACCTTC ATACCTTCC TACCTTCCC ACCTTCCCA CCTTCCCAG CTTCCCAGG TTCCCAGGT TCCCAGGTA CCCAGGTAA CCAGGTAAC CAGGTAACA AGGTAACAA GGTAACAAA GTAACAAAC TAACAAACC AACAAACCA ACAAACCAA CAAACCAAC AAACCAACC AACCAACCA ACCAACCAA CCAACCAAC CAACCAACT AACCAACTT ACCAACTTT CCAACTTTC CAACTTTCG AACTTTCGA ACTTTCGAT CTTTCGATC TTTCGATCT TTCGATCTC TCGATCTCT CGATCTCTT GATCTCTTG ATCTCTTGT TCTCTTGTA CTCTTGTAG TCTTGTAGA CTTGTAGAT TTGTAGATC TGTAGATCT GTAGATCTG TAGATCTGT AGATCTGTT GATCTGTTC ATCTGTTCT TCTGTTCTC CTGTTCTCT TGTTCTCTA GTTCTCTAA TTCTCTAAA TCTCTAAAC CTCTAAACG TCTAAACGA CTAAACGAA TAAACGAAC AAACGAACT AACGAACTT ACGAACTTT CGAACTTTA GAACTTTAA AACTTTAAA ACTTTAAAA CTTTAAAAT TTTAAAATC TTAAAATCT TAAAATCTG AAAATCTGT AAATCTGTG AATCTGTGT ATCTGTGTG TCTGTGTGG CTGTGTGGC TGTGTGGCT GTGTGGCTG TGTGGCTGT GTGGCTGTC TGGCTGTCA GGCTGTCAC GCTGTCACT CTGTCACTC TGTCACTCG GTCACTCGG TCACTCGGC CACTCGGCT ACTCGGCTG CTCGGCTGC TCGGCTGCA CGGCTGCAT GGCTGCATG GCTGCATGC CTGCATGCT TGCATGCTT GCATGCTTA CATGCTTAG ATGCTTAGT TGCTTAGTG GCTTAGTGC CTTAGTGCA TTAGTGCAC TAGTGCACT AGTGCACTC GTGCACTCA TGCACTCAC GCACTCACG CACTCACGC ACTCACGCA CTCACGCAG TCACGCAGT CACGCAGTA ACGCAGTAT CGCAGTATA GCAGTATAA CAGTATAAT AGTATAATT GTATAATTA TATAATTAA ATAATTAAT TAATTAATA AATTAATAA ATTAATAAC TTAATAACT TAATAACTA AATAACTAA ATAACTAAT TAACTAATT AACTAATTA ACTAATTAC CTAATTACT TAATTACTG AATTACTGT ATTACTGTC TTACTGTCG TACTGTCGT ACTGTCGTT CTGTCGTTG TGTCGTTGA GTCGTTGAC TCGTTGACA CGTTGACAG GTTGACAGG TTGACAGGA TGACAGGAC GACAGGACA ACAGGACAC CAGGACACG AGGACACGA GGACACGAG GACACGAGT ACACGAGTA CACGAGTAA ACGAGTAAC CGAGTAACT GAGTAACTC AGTAACTCG GTAACTCGT TAACTCGTC AACTCGTCT ACTCGTCTA CTCGTCTAT TCGTCTATC CGTCTATCT GTCTATCTT TCTATCTTC CTATCTTCT TATCTTCTG ATCTTCTGC TCTTCTGCA CTTCTGCAG TTCTGCAGG TCTGCAGGC CTGCAGGCT TGCAGGCTG GCAGGCTGC CAGGCTGCT AGGCTGCTT GGCTGCTTA GCTGCTTAC CTGCTTACG TGCTTACGG GCTTACGGT CTTACGGTT TTACGGTTT TACGGTTTC ACGGTTTCG CGGTTTCGT GGTTTCGTC GTTTCGTCC TTTCGTCCG TTCGTCCGT TCGTCCGTG CGTCCGTGT GTCCGTGTT TCCGTGTTG CCGTGTTGC CGTGTTGCA GTGTTGCAG TGTTGCAGC GTTGCAGCC TTGCAGCCG TGCAGCCGA GCAGCCGAT CAGCCGATC AGCCGATCA GCCGATCAT CCGATCATC CGATCATCA GATCATCAG ATCATCAGC TCATCAGCA CATCAGCAC ATCAGCACA TCAGCACAT CAGCACATC AGCACATCT GCACATCTA CACATCTAG ACATCTAGG CATCTAGGT ATCTAGGTT TCTAGGTTT CTAGGTTTT TAGGTTTTG AGGTTTTGT GGTTTTGTC GTTTTGTCC TTTTGTCCG TTTGTCCGG TTGTCCGGG TGTCCGGGT GTCCGGGTG TCCGGGTGT CCGGGTGTG CGGGTGTGA GGGTGTGAC GGTGTGACC GTGTGACCG TGTGACCGA GTGACCGAA TGACCGAAA GACCGAAAG ACCGAAAGG CCGAAAGGT CGAAAGGTA GAAAGGTAA AAAGGTAAG AAGGTAAGA AGGTAAGAT GGTAAGATG GTAAGATGG TAAGATGGA AAGATGGAG AGATGGAGA GATGGAGAG ATGGAGAGC TGGAGAGCC GGAGAGCCT GAGAGCCTT AGAGCCTTG GAGCCTTGT AGCCTTGTC GCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTG TGTCCCTGG GTCCCTGGT TCCCTGGTT CCCTGGTTT CCTGGTTTC CTGGTTTCA TGGTTTCAA GGTTTCAAC GTTTCAACG TTTCAACGA TTCAACGAG TCAACGAGA CAACGAGAA AACGAGAAA ACGAGAAAA CGAGAAAAC GAGAAAACA AGAAAACAC GAAAACACA AAAACACAC AAACACACG AACACACGT ACACACGTC CACACGTCC ACACGTCCA CACGTCCAA ACGTCCAAC CGTCCAACT GTCCAACTC TCCAACTCA CCAACTCAG CAACTCAGT AACTCAGTT ACTCAGTTT CTCAGTTTG TCAGTTTGC CAGTTTGCC AGTTTGCCT GTTTGCCTG TTTGCCTGT TTGCCTGTT TGCCTGTTT GCCTGTTTT CCTGTTTTA CTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGG TTTACAGGT TTACAGGTT TACAGGTTC ACAGGTTCG CAGGTTCGC AGGTTCGCG GGTTCGCGA GTTCGCGAC TTCGCGACG TCGCGACGT CGCGACGTG GCGACGTGC CGACGTGCT GACGTGCTC ACGTGCTCG CGTGCTCGT GTGCTCGTA TGCTCGTAC GCTCGTACG CTCGTACGT TCGTACGTG CGTACGTGG GTACGTGGC TACGTGGCT ACGTGGCTT CGTGGCTTT GTGGCTTTG TGGCTTTGG GGCTTTGGA GCTTTGGAG CTTTGGAGA TTTGGAGAC TTGGAGACT TGGAGACTC GGAGACTCC GAGACTCCG AGACTCCGT GACTCCGTG ACTCCGTGG CTCCGTGGA TCCGTGGAG CCGTGGAGG CGTGGAGGA GTGGAGGAG TGGAGGAGG GGAGGAGGT GAGGAGGTC AGGAGGTCT GGAGGTCTT GAGGTCTTA AGGTCTTAT GGTCTTATC GTCTTATCA TCTTATCAG CTTATCAGA TTATCAGAG TATCAGAGG ATCAGAGGC TCAGAGGCA CAGAGGCAC AGAGGCACG GAGGCACGT AGGCACGTC GGCACGTCA GCACGTCAA CACGTCAAC ACGTCAACA CGTCAACAT GTCAACATC TCAACATCT CAACATCTT AACATCTTA ACATCTTAA CATCTTAAA ATCTTAAAG TCTTAAAGA CTTAAAGAT TTAAAGATG TAAAGATGG AAAGATGGC AAGATGGCA AGATGGCAC GATGGCACT ATGGCACTT TGGCACTTG GGCACTTGT GCACTTGTG CACTTGTGG ACTTGTGGC CTTGTGGCT TTGTGGCTT TGTGGCTTA GTGGCTTAG TGGCTTAGT GGCTTAGTA GCTTAGTAG CTTAGTAGA TTAGTAGAA TAGTAGAAG AGTAGAAGT GTAGAAGTT TAGAAGTTG AGAAGTTGA GAAGTTGAA AAGTTGAAA AGTTGAAAA GTTGAAAAA TTGAAAAAG TGAAAAAGG GAAAAAGGC AAAAAGGCG AAAAGGCGT AAAGGCGTT AAGGCGTTT AGGCGTTTT GGCGTTTTG GCGTTTTGC CGTTTTGCC GTTTTGCCT TTTTGCCTC TTTGCCTCA TTGCCTCAA TGCCTCAAC GCCTCAACT CCTCAACTT CTCAACTTG TCAACTTGA CAACTTGAA AACTTGAAC ACTTGAACA CTTGAACAG TTGAACAGC TGAACAGCC GAACAGCCC AACAGCCCT ACAGCCCTA CAGCCCTAT AGCCCTATG GCCCTATGT CCCTATGTG CCTATGTGT CTATGTGTT TATGTGTTC ATGTGTTCA TGTGTTCAT GTGTTCATC TGTTCATCA GTTCATCAA TTCATCAAA TCATCAAAC CATCAAACG ATCAAACGT TCAAACGTT CAAACGTTC AAACGTTCG AACGTTCGG ACGTTCGGA CGTTCGGAT GTTCGGATG TTCGGATGC TCGGATGCT CGGATGCTC GGATGCTCG GATGCTCGA ATGCTCGAA TGCTCGAAC GCTCGAACT CTCGAACTG TCGAACTGC CGAACTGCA GAACTGCAC AACTGCACC ACTGCACCT CTGCACCTC TGCACCTCA GCACCTCAT CACCTCATG ACCTCATGG CCTCATGGT CTCATGGTC TCATGGTCA CATGGTCAT ATGGTCATG TGGTCATGT GGTCATGTT GTCATGTTA TCATGTTAT CATGTTATG ATGTTATGG TGTTATGGT GTTATGGTT TTATGGTTG TATGGTTGA ATGGTTGAG TGGTTGAGC GGTTGAGCT GTTGAGCTG TTGAGCTGG TGAGCTGGT GAGCTGGTA AGCTGGTAG GCTGGTAGC CTGGTAGCA TGGTAGCAG GGTAGCAGA GTAGCAGAA TAGCAGAAC AGCAGAACT GCAGAACTC CAGAACTCG AGAACTCGA GAACTCGAA AACTCGAAG ACTCGAAGG CTCGAAGGC TCGAAGGCA CGAAGGCAT GAAGGCATT AAGGCATTC AGGCATTCA GGCATTCAG GCATTCAGT CATTCAGTA ATTCAGTAC TTCAGTACG TCAGTACGG CAGTACGGT AGTACGGTC GTACGGTCG TACGGTCGT ACGGTCGTA CGGTCGTAG GGTCGTAGT GTCGTAGTG TCGTAGTGG CGTAGTGGT GTAGTGGTG TAGTGGTGA AGTGGTGAG GTGGTGAGA TGGTGAGAC GGTGAGACA GTGAGACAC TGAGACACT GAGACACTT AGACACTTG GACACTTGG ACACTTGGT CACTTGGTG ACTTGGTGT CTTGGTGTC TTGGTGTCC TGGTGTCCT GGTGTCCTT GTGTCCTTG TGTCCTTGT GTCCTTGTC TCCTTGTCC CCTTGTCCC CTTGTCCCT TTGTCCCTC TGTCCCTCA GTCCCTCAT TCCCTCATG CCCTCATGT CCTCATGTG CTCATGTGG TCATGTGGG CATGTGGGC ATGTGGGCG TGTGGGCGA GTGGGCGAA TGGGCGAAA GGGCGAAAT GGCGAAATA GCGAAATAC CGAAATACC GAAATACCA AAATACCAG AATACCAGT ATACCAGTG TACCAGTGG ACCAGTGGC CCAGTGGCT CAGTGGCTT AGTGGCTTA GTGGCTTAC TGGCTTACC GGCTTACCG GCTTACCGC CTTACCGCA TTACCGCAA TACCGCAAG ACCGCAAGG CCGCAAGGT CGCAAGGTT GCAAGGTTC CAAGGTTCT AAGGTTCTT AGGTTCTTC GGTTCTTCT GTTCTTCTT TTCTTCTTC TCTTCTTCG CTTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGA TCGTAAGAA CGTAAGAAC GTAAGAACG TAAGAACGG AAGAACGGT AGAACGGTA GAACGGTAA AACGGTAAT ACGGTAATA CGGTAATAA GGTAATAAA GTAATAAAG TAATAAAGG AATAAAGGA ATAAAGGAG TAAAGGAGC AAAGGAGCT AAGGAGCTG AGGAGCTGG GGAGCTGGT GAGCTGGTG AGCTGGTGG GCTGGTGGC CTGGTGGCC TGGTGGCCA GGTGGCCAT GTGGCCATA TGGCCATAG GGCCATAGT GCCATAGTT CCATAGTTA CATAGTTAC ATAGTTACG TAGTTACGG AGTTACGGC GTTACGGCG TTACGGCGC TACGGCGCC ACGGCGCCG CGGCGCCGA GGCGCCGAT GCGCCGATC CGCCGATCT GCCGATCTA CCGATCTAA CGATCTAAA GATCTAAAG ATCTAAAGT TCTAAAGTC CTAAAGTCA TAAAGTCAT AAAGTCATT AAGTCATTT AGTCATTTG GTCATTTGA TCATTTGAC CATTTGACT ATTTGACTT TTTGACTTA TTGACTTAG TGACTTAGG GACTTAGGC ACTTAGGCG CTTAGGCGA TTAGGCGAC TAGGCGACG AGGCGACGA GGCGACGAG GCGACGAGC CGACGAGCT GACGAGCTT ACGAGCTTG CGAGCTTGG GAGCTTGGC AGCTTGGCA GCTTGGCAC CTTGGCACT TTGGCACTG TGGCACTGA GGCACTGAT GCACTGATC CACTGATCC ACTGATCCT CTGATCCTT TGATCCTTA GATCCTTAT ATCCTTATG TCCTTATGA CCTTATGAA CTTATGAAG TTATGAAGA TATGAAGAT ATGAAGATT TGAAGATTT GAAGATTTT AAGATTTTC AGATTTTCA GATTTTCAA ATTTTCAAG TTTTCAAGA TTTCAAGAA TTCAAGAAA TCAAGAAAA CAAGAAAAC AAGAAAACT AGAAAACTG GAAAACTGG AAAACTGGA AAACTGGAA AACTGGAAC ACTGGAACA CTGGAACAC TGGAACACT GGAACACTA GAACACTAA AACACTAAA ACACTAAAC CACTAAACA ACTAAACAT CTAAACATA TAAACATAG AAACATAGC AACATAGCA ACATAGCAG CATAGCAGT ATAGCAGTG TAGCAGTGG AGCAGTGGT GCAGTGGTG CAGTGGTGT AGTGGTGTT GTGGTGTTA TGGTGTTAC GGTGTTACC GTGTTACCC TGTTACCCG GTTACCCGT TTACCCGTG TACCCGTGA ACCCGTGAA CCCGTGAAC CCGTGAACT CGTGAACTC GTGAACTCA TGAACTCAT GAACTCATG AACTCATGC ACTCATGCG CTCATGCGT TCATGCGTG CATGCGTGA ATGCGTGAG TGCGTGAGC GCGTGAGCT CGTGAGCTT GTGAGCTTA TGAGCTTAA GAGCTTAAC AGCTTAACG GCTTAACGG CTTAACGGA TTAACGGAG TAACGGAGG AACGGAGGG ACGGAGGGG CGGAGGGGC GGAGGGGCA GAGGGGCAT AGGGGCATA GGGGCATAC GGGCATACA GGCATACAC GCATACACT CATACACTC ATACACTCG TACACTCGC ACACTCGCT CACTCGCTA ACTCGCTAT CTCGCTATG TCGCTATGT CGCTATGTC GCTATGTCG CTATGTCGA TATGTCGAT ATGTCGATA TGTCGATAA GTCGATAAC TCGATAACA CGATAACAA GATAACAAC ATAACAACT TAACAACTT AACAACTTC ACAACTTCT CAACTTCTG AACTTCTGT ACTTCTGTG CTTCTGTGG TTCTGTGGC TCTGTGGCC CTGTGGCCC TGTGGCCCT GTGGCCCTG TGGCCCTGA GGCCCTGAT GCCCTGATG CCCTGATGG CCTGATGGC CTGATGGCT TGATGGCTA GATGGCTAC ATGGCTACC TGGCTACCC GGCTACCCT GCTACCCTC CTACCCTCT TACCCTCTT ACCCTCTTG CCCTCTTGA CCTCTTGAG CTCTTGAGT TCTTGAGTG CTTGAGTGC TTGAGTGCA TGAGTGCAT GAGTGCATT AGTGCATTA GTGCATTAA TGCATTAAA GCATTAAAG CATTAAAGA ATTAAAGAC TTAAAGACC TAAAGACCT AAAGACCTT AAGACCTTC AGACCTTCT GACCTTCTA ACCTTCTAG CCTTCTAGC CTTCTAGCA TTCTAGCAC TCTAGCACG CTAGCACGT TAGCACGTG AGCACGTGC GCACGTGCT CACGTGCTG ACGTGCTGG CGTGCTGGT GTGCTGGTA TGCTGGTAA GCTGGTAAA CTGGTAAAG TGGTAAAGC GGTAAAGCT GTAAAGCTT TAAAGCTTC AAAGCTTCA AAGCTTCAT AGCTTCATG GCTTCATGC CTTCATGCA TTCATGCAC TCATGCACT CATGCACTT ATGCACTTT TGCACTTTG GCACTTTGT CACTTTGTC ACTTTGTCC CTTTGTCCG TTTGTCCGA TTGTCCGAA TGTCCGAAC GTCCGAACA TCCGAACAA CCGAACAAC CGAACAACT GAACAACTG AACAACTGG ACAACTGGA CAACTGGAC AACTGGACT ACTGGACTT CTGGACTTT TGGACTTTA GGACTTTAT GACTTTATT ACTTTATTG CTTTATTGA TTTATTGAC TTATTGACA TATTGACAC ATTGACACT TTGACACTA TGACACTAA GACACTAAG ACACTAAGA CACTAAGAG ACTAAGAGG CTAAGAGGG TAAGAGGGG AAGAGGGGT AGAGGGGTG GAGGGGTGT AGGGGTGTA GGGGTGTAT GGGTGTATA GGTGTATAC GTGTATACT TGTATACTG GTATACTGC TATACTGCT ATACTGCTG TACTGCTGC ACTGCTGCC CTGCTGCCG TGCTGCCGT GCTGCCGTG CTGCCGTGA TGCCGTGAA GCCGTGAAC CCGTGAACA CGTGAACAT GTGAACATG TGAACATGA GAACATGAG AACATGAGC ACATGAGCA CATGAGCAT ATGAGCATG TGAGCATGA GAGCATGAA AGCATGAAA GCATGAAAT CATGAAATT ATGAAATTG TGAAATTGC GAAATTGCT AAATTGCTT AATTGCTTG ATTGCTTGG TTGCTTGGT TGCTTGGTA GCTTGGTAC CTTGGTACA TTGGTACAC TGGTACACG GGTACACGG GTACACGGA TACACGGAA ACACGGAAC CACGGAACG ACGGAACGT CGGAACGTT GGAACGTTC GAACGTTCT AACGTTCTG ACGTTCTGA CGTTCTGAA GTTCTGAAA TTCTGAAAA TCTGAAAAG CTGAAAAGA TGAAAAGAG GAAAAGAGC AAAAGAGCT AAAGAGCTA AAGAGCTAT AGAGCTATG GAGCTATGA AGCTATGAA GCTATGAAT CTATGAATT TATGAATTG ATGAATTGC TGAATTGCA GAATTGCAG AATTGCAGA ATTGCAGAC TTGCAGACA TGCAGACAC GCAGACACC CAGACACCT AGACACCTT GACACCTTT ACACCTTTT CACCTTTTG ACCTTTTGA CCTTTTGAA CTTTTGAAA TTTTGAAAT TTTGAAATT TTGAAATTA TGAAATTAA GAAATTAAA AAATTAAAT AATTAAATT ATTAAATTG TTAAATTGG TAAATTGGC AAATTGGCA AATTGGCAA ATTGGCAAA TTGGCAAAG TGGCAAAGA GGCAAAGAA GCAAAGAAA CAAAGAAAT AAAGAAATT AAGAAATTT AGAAATTTG GAAATTTGA AAATTTGAC AATTTGACA ATTTGACAC TTTGACACC TTGACACCT TGACACCTT GACACCTTC ACACCTTCA CACCTTCAA ACCTTCAAT CCTTCAATG CTTCAATGG TTCAATGGG TCAATGGGG CAATGGGGA AATGGGGAA ATGGGGAAT TGGGGAATG GGGGAATGT GGGAATGTC GGAATGTCC GAATGTCCA AATGTCCAA ATGTCCAAA TGTCCAAAT GTCCAAATT TCCAAATTT CCAAATTTT CAAATTTTG AAATTTTGT AATTTTGTA ATTTTGTAT TTTTGTATT TTTGTATTT TTGTATTTC TGTATTTCC GTATTTCCC TATTTCCCT ATTTCCCTT TTTCCCTTA TTCCCTTAA TCCCTTAAA CCCTTAAAT CCTTAAATT CTTAAATTC TTAAATTCC TAAATTCCA AAATTCCAT AATTCCATA ATTCCATAA TTCCATAAT TCCATAATC CCATAATCA CATAATCAA ATAATCAAG TAATCAAGA AATCAAGAC ATCAAGACT TCAAGACTA CAAGACTAT AAGACTATT AGACTATTC GACTATTCA ACTATTCAA CTATTCAAC TATTCAACC ATTCAACCA TTCAACCAA TCAACCAAG CAACCAAGG AACCAAGGG ACCAAGGGT CCAAGGGTT CAAGGGTTG AAGGGTTGA AGGGTTGAA GGGTTGAAA GGTTGAAAA GTTGAAAAG TTGAAAAGA TGAAAAGAA GAAAAGAAA AAAAGAAAA AAAGAAAAA AAGAAAAAG AGAAAAAGC GAAAAAGCT AAAAAGCTT AAAAGCTTG AAAGCTTGA AAGCTTGAT AGCTTGATG GCTTGATGG CTTGATGGC TTGATGGCT TGATGGCTT GATGGCTTT ATGGCTTTA TGGCTTTAT GGCTTTATG GCTTTATGG CTTTATGGG TTTATGGGT TTATGGGTA TATGGGTAG ATGGGTAGA TGGGTAGAA GGGTAGAAT GGTAGAATT GTAGAATTC TAGAATTCG AGAATTCGA GAATTCGAT AATTCGATC ATTCGATCT TTCGATCTG TCGATCTGT CGATCTGTC GATCTGTCT ATCTGTCTA TCTGTCTAT CTGTCTATC TGTCTATCC GTCTATCCA TCTATCCAG CTATCCAGT TATCCAGTT ATCCAGTTG TCCAGTTGC CCAGTTGCG CAGTTGCGT AGTTGCGTC GTTGCGTCA TTGCGTCAC TGCGTCACC GCGTCACCA CGTCACCAA GTCACCAAA TCACCAAAT CACCAAATG ACCAAATGA CCAAATGAA CAAATGAAT AAATGAATG AATGAATGC ATGAATGCA TGAATGCAA GAATGCAAC AATGCAACC ATGCAACCA TGCAACCAA GCAACCAAA CAACCAAAT AACCAAATG ACCAAATGT CCAAATGTG CAAATGTGC AAATGTGCC AATGTGCCT ATGTGCCTT TGTGCCTTT GTGCCTTTC TGCCTTTCA GCCTTTCAA CCTTTCAAC CTTTCAACT TTTCAACTC TTCAACTCT TCAACTCTC CAACTCTCA AACTCTCAT ACTCTCATG CTCTCATGA TCTCATGAA CTCATGAAG TCATGAAGT CATGAAGTG ATGAAGTGT TGAAGTGTG GAAGTGTGA AAGTGTGAT AGTGTGATC GTGTGATCA TGTGATCAT GTGATCATT TGATCATTG GATCATTGT ATCATTGTG TCATTGTGG CATTGTGGT ATTGTGGTG TTGTGGTGA TGTGGTGAA GTGGTGAAA TGGTGAAAC GGTGAAACT GTGAAACTT TGAAACTTC GAAACTTCA AAACTTCAT AACTTCATG ACTTCATGG CTTCATGGC TTCATGGCA TCATGGCAG CATGGCAGA ATGGCAGAC TGGCAGACG GGCAGACGG GCAGACGGG CAGACGGGC AGACGGGCG GACGGGCGA ACGGGCGAT CGGGCGATT GGGCGATTT GGCGATTTT GCGATTTTG CGATTTTGT GATTTTGTT ATTTTGTTA TTTTGTTAA TTTGTTAAA TTGTTAAAG TGTTAAAGC GTTAAAGCC TTAAAGCCA TAAAGCCAC AAAGCCACT AAGCCACTT AGCCACTTG GCCACTTGC CCACTTGCG CACTTGCGA ACTTGCGAA CTTGCGAAT TTGCGAATT TGCGAATTT GCGAATTTT CGAATTTTG GAATTTTGT AATTTTGTG ATTTTGTGG TTTTGTGGC TTTGTGGCA TTGTGGCAC TGTGGCACT GTGGCACTG TGGCACTGA GGCACTGAG GCACTGAGA CACTGAGAA ACTGAGAAT CTGAGAATT TGAGAATTT GAGAATTTG AGAATTTGA GAATTTGAC AATTTGACT ATTTGACTA TTTGACTAA TTGACTAAA TGACTAAAG GACTAAAGA ACTAAAGAA CTAAAGAAG TAAAGAAGG AAAGAAGGT AAGAAGGTG AGAAGGTGC GAAGGTGCC AAGGTGCCA AGGTGCCAC GGTGCCACT GTGCCACTA TGCCACTAC GCCACTACT CCACTACTT CACTACTTG ACTACTTGT CTACTTGTG TACTTGTGG ACTTGTGGT CTTGTGGTT TTGTGGTTA TGTGGTTAC GTGGTTACT TGGTTACTT GGTTACTTA GTTACTTAC TTACTTACC TACTTACCC ACTTACCCC CTTACCCCA TTACCCCAA TACCCCAAA ACCCCAAAA CCCCAAAAT CCCAAAATG CCAAAATGC CAAAATGCT AAAATGCTG AAATGCTGT AATGCTGTT ATGCTGTTG TGCTGTTGT GCTGTTGTT CTGTTGTTA TGTTGTTAA GTTGTTAAA TTGTTAAAA TGTTAAAAT GTTAAAATT TTAAAATTT TAAAATTTA AAAATTTAT AAATTTATT AATTTATTG ATTTATTGT TTTATTGTC TTATTGTCC TATTGTCCA ATTGTCCAG TTGTCCAGC TGTCCAGCA GTCCAGCAT TCCAGCATG CCAGCATGT CAGCATGTC AGCATGTCA GCATGTCAC CATGTCACA ATGTCACAA TGTCACAAT GTCACAATT TCACAATTC CACAATTCA ACAATTCAG CAATTCAGA AATTCAGAA ATTCAGAAG TTCAGAAGT TCAGAAGTA CAGAAGTAG AGAAGTAGG GAAGTAGGA AAGTAGGAC AGTAGGACC GTAGGACCT TAGGACCTG AGGACCTGA GGACCTGAG GACCTGAGC ACCTGAGCA CCTGAGCAT CTGAGCATA TGAGCATAG GAGCATAGT AGCATAGTC GCATAGTCT CATAGTCTT ATAGTCTTG TAGTCTTGC AGTCTTGCC GTCTTGCCG TCTTGCCGA CTTGCCGAA TTGCCGAAT TGCCGAATA GCCGAATAC CCGAATACC CGAATACCA GAATACCAT AATACCATA ATACCATAA TACCATAAT ACCATAATG CCATAATGA CATAATGAA ATAATGAAT TAATGAATC AATGAATCT ATGAATCTG TGAATCTGG GAATCTGGC AATCTGGCT ATCTGGCTT TCTGGCTTG CTGGCTTGA TGGCTTGAA GGCTTGAAA GCTTGAAAA CTTGAAAAC TTGAAAACC TGAAAACCA GAAAACCAT AAAACCATT AAACCATTC AACCATTCT ACCATTCTT CCATTCTTC CATTCTTCG ATTCTTCGT TTCTTCGTA TCTTCGTAA CTTCGTAAG TTCGTAAGG TCGTAAGGG CGTAAGGGT GTAAGGGTG TAAGGGTGG AAGGGTGGT AGGGTGGTC GGGTGGTCG GGTGGTCGC GTGGTCGCA TGGTCGCAC GGTCGCACT GTCGCACTA TCGCACTAT CGCACTATT GCACTATTG CACTATTGC ACTATTGCC CTATTGCCT TATTGCCTT ATTGCCTTT TTGCCTTTG TGCCTTTGG GCCTTTGGA CCTTTGGAG CTTTGGAGG TTTGGAGGC TTGGAGGCT TGGAGGCTG GGAGGCTGT GAGGCTGTG AGGCTGTGT GGCTGTGTG GCTGTGTGT CTGTGTGTT TGTGTGTTC GTGTGTTCT TGTGTTCTC GTGTTCTCT TGTTCTCTT GTTCTCTTA TTCTCTTAT TCTCTTATG CTCTTATGT TCTTATGTT CTTATGTTG TTATGTTGG TATGTTGGT ATGTTGGTT TGTTGGTTG GTTGGTTGC TTGGTTGCC TGGTTGCCA GGTTGCCAT GTTGCCATA TTGCCATAA TGCCATAAC GCCATAACA CCATAACAA CATAACAAG ATAACAAGT TAACAAGTG AACAAGTGT ACAAGTGTG CAAGTGTGC AAGTGTGCC AGTGTGCCT GTGTGCCTA TGTGCCTAT GTGCCTATT TGCCTATTG GCCTATTGG CCTATTGGG CTATTGGGT TATTGGGTT ATTGGGTTC TTGGGTTCC TGGGTTCCA GGGTTCCAC GGTTCCACG GTTCCACGT TTCCACGTG TCCACGTGC CCACGTGCT CACGTGCTA ACGTGCTAG CGTGCTAGC GTGCTAGCG TGCTAGCGC GCTAGCGCT CTAGCGCTA TAGCGCTAA AGCGCTAAC GCGCTAACA CGCTAACAT GCTAACATA CTAACATAG TAACATAGG AACATAGGT ACATAGGTT CATAGGTTG ATAGGTTGT TAGGTTGTA AGGTTGTAA GGTTGTAAC GTTGTAACC TTGTAACCA TGTAACCAT GTAACCATA TAACCATAC AACCATACA ACCATACAG CCATACAGG CATACAGGT ATACAGGTG TACAGGTGT ACAGGTGTT CAGGTGTTG AGGTGTTGT GGTGTTGTT GTGTTGTTG TGTTGTTGG GTTGTTGGA TTGTTGGAG TGTTGGAGA GTTGGAGAA TTGGAGAAG TGGAGAAGG GGAGAAGGT GAGAAGGTT AGAAGGTTC GAAGGTTCC AAGGTTCCG AGGTTCCGA GGTTCCGAA GTTCCGAAG TTCCGAAGG TCCGAAGGT CCGAAGGTC CGAAGGTCT GAAGGTCTT AAGGTCTTA AGGTCTTAA GGTCTTAAT GTCTTAATG TCTTAATGA CTTAATGAC TTAATGACA TAATGACAA AATGACAAC ATGACAACC TGACAACCT GACAACCTT ACAACCTTC CAACCTTCT AACCTTCTT ACCTTCTTG CCTTCTTGA CTTCTTGAA TTCTTGAAA TCTTGAAAT CTTGAAATA TTGAAATAC TGAAATACT GAAATACTC AAATACTCC AATACTCCA ATACTCCAA TACTCCAAA ACTCCAAAA CTCCAAAAA TCCAAAAAG CCAAAAAGA CAAAAAGAG AAAAAGAGA AAAAGAGAA AAAGAGAAA AAGAGAAAG AGAGAAAGT GAGAAAGTC AGAAAGTCA GAAAGTCAA AAAGTCAAC AAGTCAACA AGTCAACAT GTCAACATC TCAACATCA CAACATCAA AACATCAAT ACATCAATA CATCAATAT ATCAATATT TCAATATTG CAATATTGT AATATTGTT ATATTGTTG TATTGTTGG ATTGTTGGT TTGTTGGTG TGTTGGTGA GTTGGTGAC TTGGTGACT TGGTGACTT GGTGACTTT GTGACTTTA TGACTTTAA GACTTTAAA ACTTTAAAC CTTTAAACT TTTAAACTT TTAAACTTA TAAACTTAA AAACTTAAT AACTTAATG ACTTAATGA CTTAATGAA TTAATGAAG TAATGAAGA AATGAAGAG ATGAAGAGA TGAAGAGAT GAAGAGATC AAGAGATCG AGAGATCGC GAGATCGCC AGATCGCCA GATCGCCAT ATCGCCATT TCGCCATTA CGCCATTAT GCCATTATT CCATTATTT CATTATTTT ATTATTTTG TTATTTTGG TATTTTGGC ATTTTGGCA TTTTGGCAT TTTGGCATC TTGGCATCT TGGCATCTT GGCATCTTT GCATCTTTT CATCTTTTT ATCTTTTTC TCTTTTTCT CTTTTTCTG TTTTTCTGC TTTTCTGCT TTTCTGCTT TTCTGCTTC TCTGCTTCC CTGCTTCCA TGCTTCCAC GCTTCCACA CTTCCACAA TTCCACAAG TCCACAAGT CCACAAGTG CACAAGTGC ACAAGTGCT CAAGTGCTT AAGTGCTTT AGTGCTTTT GTGCTTTTG TGCTTTTGT GCTTTTGTG CTTTTGTGG TTTTGTGGA TTTGTGGAA TTGTGGAAA TGTGGAAAC GTGGAAACT TGGAAACTG GGAAACTGT GAAACTGTG AAACTGTGA AACTGTGAA ACTGTGAAA CTGTGAAAG TGTGAAAGG GTGAAAGGT TGAAAGGTT GAAAGGTTT AAAGGTTTG AAGGTTTGG AGGTTTGGA GGTTTGGAT GTTTGGATT TTTGGATTA TTGGATTAT TGGATTATA GGATTATAA GATTATAAA ATTATAAAG TTATAAAGC TATAAAGCA ATAAAGCAT TAAAGCATT AAAGCATTC AAGCATTCA AGCATTCAA GCATTCAAA CATTCAAAC ATTCAAACA TTCAAACAA TCAAACAAA CAAACAAAT AAACAAATT AACAAATTG ACAAATTGT CAAATTGTT AAATTGTTG AATTGTTGA ATTGTTGAA TTGTTGAAT TGTTGAATC GTTGAATCC TTGAATCCT TGAATCCTG GAATCCTGT AATCCTGTG ATCCTGTGG TCCTGTGGT CCTGTGGTA CTGTGGTAA TGTGGTAAT GTGGTAATT TGGTAATTT GGTAATTTT GTAATTTTA TAATTTTAA AATTTTAAA ATTTTAAAG TTTTAAAGT TTTAAAGTT TTAAAGTTA TAAAGTTAC AAAGTTACA AAGTTACAA AGTTACAAA GTTACAAAA TTACAAAAG TACAAAAGG ACAAAAGGA CAAAAGGAA AAAAGGAAA AAAGGAAAA AAGGAAAAG AGGAAAAGC GGAAAAGCT GAAAAGCTA AAAAGCTAA AAAGCTAAA AAGCTAAAA AGCTAAAAA GCTAAAAAA CTAAAAAAG TAAAAAAGG AAAAAAGGT AAAAAGGTG AAAAGGTGC AAAGGTGCC AAGGTGCCT AGGTGCCTG GGTGCCTGG GTGCCTGGA TGCCTGGAA GCCTGGAAT CCTGGAATA CTGGAATAT TGGAATATT GGAATATTG GAATATTGG AATATTGGT ATATTGGTG TATTGGTGA ATTGGTGAA TTGGTGAAC TGGTGAACA GGTGAACAG GTGAACAGA TGAACAGAA GAACAGAAA AACAGAAAT ACAGAAATC CAGAAATCA AGAAATCAA GAAATCAAT AAATCAATA AATCAATAC ATCAATACT TCAATACTG CAATACTGA AATACTGAG ATACTGAGT TACTGAGTC ACTGAGTCC CTGAGTCCT TGAGTCCTC GAGTCCTCT AGTCCTCTT GTCCTCTTT TCCTCTTTA CCTCTTTAT CTCTTTATG TCTTTATGC CTTTATGCA TTTATGCAT TTATGCATT TATGCATTT ATGCATTTG TGCATTTGC GCATTTGCA CATTTGCAT ATTTGCATC TTTGCATCA TTGCATCAG TGCATCAGA GCATCAGAG CATCAGAGG ATCAGAGGC TCAGAGGCT CAGAGGCTG AGAGGCTGC GAGGCTGCT AGGCTGCTC GGCTGCTCG GCTGCTCGT CTGCTCGTG TGCTCGTGT GCTCGTGTT CTCGTGTTG TCGTGTTGT CGTGTTGTA GTGTTGTAC TGTTGTACG GTTGTACGA TTGTACGAT TGTACGATC GTACGATCA TACGATCAA ACGATCAAT CGATCAATT GATCAATTT ATCAATTTT TCAATTTTC CAATTTTCT AATTTTCTC ATTTTCTCC TTTTCTCCC TTTCTCCCG TTCTCCCGC TCTCCCGCA CTCCCGCAC TCCCGCACT CCCGCACTC CCGCACTCT CGCACTCTT GCACTCTTG CACTCTTGA ACTCTTGAA CTCTTGAAA TCTTGAAAC CTTGAAACT TTGAAACTG TGAAACTGC GAAACTGCT AAACTGCTC AACTGCTCA ACTGCTCAA CTGCTCAAA TGCTCAAAA GCTCAAAAT CTCAAAATT TCAAAATTC CAAAATTCT AAAATTCTG AAATTCTGT AATTCTGTG ATTCTGTGC TTCTGTGCG TCTGTGCGT CTGTGCGTG TGTGCGTGT GTGCGTGTT TGCGTGTTT GCGTGTTTT CGTGTTTTA GTGTTTTAC TGTTTTACA GTTTTACAG TTTTACAGA TTTACAGAA TTACAGAAG TACAGAAGG ACAGAAGGC CAGAAGGCC AGAAGGCCG GAAGGCCGC AAGGCCGCT AGGCCGCTA GGCCGCTAT GCCGCTATA CCGCTATAA CGCTATAAC GCTATAACA CTATAACAA TATAACAAT ATAACAATA TAACAATAC AACAATACT ACAATACTA CAATACTAG AATACTAGA ATACTAGAT TACTAGATG ACTAGATGG CTAGATGGA TAGATGGAA AGATGGAAT GATGGAATT ATGGAATTT TGGAATTTC GGAATTTCA GAATTTCAC AATTTCACA ATTTCACAG TTTCACAGT TTCACAGTA TCACAGTAT CACAGTATT ACAGTATTC CAGTATTCA AGTATTCAC GTATTCACT TATTCACTG ATTCACTGA TTCACTGAG TCACTGAGA CACTGAGAC ACTGAGACT CTGAGACTC TGAGACTCA GAGACTCAT AGACTCATT GACTCATTG

# CountVectorizer

In [ ]:
# Read csv


# Iterate through corpus
# CountVectorizer

# References

* Correct Way To Parse A Fasta File In Python: https://www.biostars.org/p/710/
* Biopython tutorial: https://biopython.org/DIST/docs/tutorial/Tutorial.html#sec12
* SeqIO: https://biopython.org/wiki/SeqIO
* AlignIO: https://biopython.org/wiki/AlignIO
* How to concatenate DataFrames: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html